### ISSUE TITLE
Performance edge-case issue in SystemNodeProvider

### ISSUE THREAD

**Issue by aztech-dev** [ramsey/uuid#107]
As discussed [here](https://github.com/ramsey/uuid/commit/7fe43508a40846d1b0ce1ec78d1bf67e9faac8dd#commitcomment-16831130) with @jmauerhan , there is a performance issue in SystemNodeProvider for environments where the MAC address cannot be extracted from network interface configuration output.

In order to preserve BC, `SystemNodeProvider` should also provide a mechanism for caching "failed" MAC address detection, otherwise an `exec` call is used everytime that `SystemNodeProvider::getNode()` is called.

Example cases where this could happen:

- Setups where the `ifconfig` (or OS specific variant) is not available
- User does not have sufficient rights to run `ifconfig` (or OS specific variant)

**Comment by ramsey** [comment]
Resolved in #121.
