### ISSUE TITLE
Set lowest PHP version requirement to 7.0

### ISSUE THREAD

**Issue by ramsey** [ramsey/uuid#110]
PHP 5.4 is already end-of-life, and 5.5 will EOL on 10 Jul 2016. PHP 5.6 is supported until 31 Dec 2018.

See http://php.net/supported-versions.php

**Comment by GrahamCampbell** [comment]
:+1: for dropping 5.4 asap. I think it might be best to hold off on 5.5 for a few months though. Only a few months though. I still want to see it gone. ;)

**Comment by ramsey** [comment]
I probably won't release a 4.0.0 until after 10 July, so I think having 5.6 as the lowest supported version will be fine.

**Comment by GrahamCampbell** [comment]
Great. ;)

**Comment by Spomky** [comment]
Because PHP 5.6 active support will end by the end of the month and v4.0 has not yet been released, PHP 7.0 could be the minimal requirement for the next major version.
The other benefit is that you can remove the `paragonie/random_compat`.

**Comment by GrahamCampbell** [comment]
> Because PHP 5.6 active support will end by the end of the month

Not true. Support for php 5.6 has been extended, beyond 7.0 actually.

---

![image](https://cloud.githubusercontent.com/assets/2829600/21063756/35285098-be4f-11e6-9293-c2d3ef98f285.png)
![image](https://cloud.githubusercontent.com/assets/2829600/21063761/3a54a06c-be4f-11e6-8e91-c87bb1377af1.png)

**Comment by GrahamCampbell** [comment]
Oh, active support, meh, well, security support is all that really matters imo. If there are other bugs that don't affect the library in php 5.6, after that point, that's fine, it doesn't affect the library.

**Comment by Potherca** [comment]
In issue #186 @ramsey has stated

> the next major version of `ramsey/uuid` will target PHP 7+ only

Shouldn't the title of this issue be changes to "_Set lowest PHP version requirement to 7.0_"?

**Comment by ramsey** [comment]
Title changed to use `7.0`, given the changes introduced through #189.
