### ISSUE TITLE
__toString() in UuidInterface

### ISSUE THREAD

**Issue by danizord** [ramsey/uuid#111]
Oh, I've heard on Twitter something about 4.0 :P

So, speaking about that, there's something that always bother me. I like to cast UUID objects to string for persistence and representation, but there's no `__toString()` method in `UuidInterface`.

Ok, I could typehint against `Uuid` class, but if I do that, PHPStorm complains that return type of `Uuid::uuid4()` (`UuidInterface`) is not compatible with the expected type (`Uuid`). 

So, could you add `__toString()` method in `UuidInterface` for next 4.0 version?

**Comment by jmauerhan** [comment]
It's typically best in OOP to pass around objects rather than scalar values, so using the object instead of the string is a good idea, and you can typehint against the `UuidInterface` instead of `Uuid`, and you won't get that error message. 

`UuidInterface` already has `toString` which is what `Uuid::__toString` calls.

**Comment by ramsey** [comment]
No promises right now, but I'll consider the implications of adding `__toString()` to the `UuidInterface` to ensure that all UUIDs can be treated like a string.

**Comment by danizord** [comment]
Hey @jmauerhan

>It's typically best in OOP to pass around objects rather than scalar values, so using the object instead of the string is a good idea.

Yeah, I pass objects around, but for serialization and representation in HTTP context I need to cast it to string. That's why all value objects that can be serialized to string tend to have a `__toString()` method.

> you can typehint against the UuidInterface instead of Uuid, and you won't get that error message

But if I do that, I can't cast it to string because I can't make sure that `__toString()` method is implemented.

> UuidInterface already has toString which is what Uuid::__toString calls. Maybe that will help? :)

That's what I do currently, but `(string) $id` just feels better :P so I'd like to have it possible in 4.0.

**Comment by sserbin** [comment]
> No promises right now, but I'll consider the implications of adding __toString() to the UuidInterface to ensure that all UUIDs can be treated like a string.

@ramsey any update on this? Would be nice to finally have this

**Comment by ramsey** [comment]
I'll add `__toString()` to version 4, but I can't add it to the interface on version 3.x, since that might break a lot of implementations.

I plan to make a big push to finish up all the things I want to implement for version 4 over the next couple of months. I'd like to have it out by the end of June.

**Comment by Yamakasi** [comment]
I'm just looking into this as well, what is the right usage for Typehinting when you have a HEX instead if a dashed UUID ?

**Comment by ramsey** [comment]
When you cast the `Uuid` object to a string, it is presented in the dashed, hexadecimal format. For type-hinting, it is a `string`.

**Comment by Yamakasi** [comment]
OK, the class itself doesn't check for a valid string, that could be done on the construct, etc so you can typehint `Uuid`.

**Comment by uphlewis** [comment]
@Yamakasi see Ramsey\Uuid\Exception\InvalidUuidStringException which gets thrown when you attempt to use Uuid::fromString() on an invalid Uuid
