### ISSUE TITLE
you code is very very very very difficult to read

### ISSUE THREAD

**Issue by angelandy** [ramsey/uuid#113]
you code is very very very very difficult to read.

**Comment by ramsey** [comment]
Do you have a specific question about how to use the library that I can help with?

**Comment by angelandy** [comment]
In fact, I just want to see what uuid1 did,
However, you do not know how many classes I have looked at, probably more than 20.
That is the most Wordy PHP code i have saw.

But also to thank you for your code, I already know what uuid1 did.

**Comment by ramsey** [comment]
The README has examples in it that should help make it clear how to use the library. If they aren’t clear, please let me know how I can improve them to make them easier to follow.

**Comment by thejahweh** [comment]
This is a very good example for over complicated code 👍 thanks
