### ISSUE TITLE
Global namespace collision in ramsay/uuid 3.3 or pre-requisite

### ISSUE THREAD

**Issue by eparisca** [ramsey/uuid#115]
As soon as I upgraded from 3.2 to 3.3 via composer, my servers started reporting the following PHP Fatal error: 

PHP Fatal error:  Call to undefined method Error::GetXML() in [script name]

Downgrading to 3.2, which also removes the prerequisite [paragonie/random_compat v2.0.2](https://github.com/paragonie/random_compat), fixed the issue. At this point i'm not sure yet if the source of this namespace collision is within ramsey/uuid or the new prerequisite.

Cheers.

**Comment by eparisca** [comment]
Issue appears to be in paragonie/random_compat extending Exception with the global name Error.

```
 // We can't really avoid making this extend Exception in PHP 5.
class Error extends Exception
```

See: 
https://github.com/paragonie/random_compat/blob/master/lib/error_polyfill.php

**Comment by eparisca** [comment]
Reported [paragonie/random_compat issue #104](https://github.com/paragonie/random_compat/issues/104)

I will leave this issue open here at the discretion of the contributors, since it will affect users upgrading to ramsey/uuid 3.3.

Cheers.

**Comment by ramsey** [comment]
Thanks for the report. random_compat does that to provide compatibility with PHP 7, which has a global Error class that extends Exception. I'll close this for now, as I don't think this will affect too many people, and especially as people prepare for upgrading to PHP 7, they'll need to be aware of the built-in Error class and change their names.
