### ISSUE TITLE
Select random rows (efficiently) with UUID

### ISSUE THREAD

**Issue by jckeen** [ramsey/uuid#119]
I've spoken with Ramsey and got his blessing first before opening this issue (because it's not really an 'issue'). 

I'm finding it necessary to return multiple random rows while using UUID. Most of the efficient means of doing so require using an auto incrementing primary key. While I can select one record randomly by using an offset clause, I feel like there has to be a better way of selecting a random UUID and then getting multiple random rows at the same time. This will stop the issue of having to COUNT the rows for an offset as well as only having to hit the database once. 

Any ideas? I'm stuck using the offset clause for now. I'm currently using MySQL.

**Comment by moderndeveloperllc** [comment]
@jckeen Just so others don't post this, I'm assuming that your dataset is too large for `SELECT * FROM table_name ORDER BY RAND() LIMIT 10;` to be performant? Or pulling your dataset into your program and doing the randomization there(`array_rand()`, etc)?

**Comment by jckeen** [comment]
@moderndeveloperllc Yes, thanks for clarifying that, I should have! 

It has the capability of becoming too large for those two solutions. I could cache the dataset (and use` array_rand()` ) once a day and pull from there, but there's still that feeling of a better way, especially with large amounts of data.

**Comment by jmauerhan** [comment]
Is there a reason you can't have an auto incrementing key that you use simply for random ordering, and not as the primary key? That way you could use the existing efficient solutions?

**Comment by ramsey** [comment]
I think @jmauerhan's recommendation is probably the best solution for this.

**Comment by jckeen** [comment]
Yes, you could make a column with an auto incrementing key as well.

Messed around a bit. I converted the first six characters of the UUID to a HEX, then used that as the basis of my selection.  It seems to be pretty performant and random, going to do some more testing. 

Any thoughts? Credit to http://mysql.rjweb.org/doc.php/random for his post that helped me out. 
You could also use an application cache in order to utitilize the benefits of the SET. 

```SQL
SET @max := (SELECT MIN(HEX(LEFT(id, 6))) FROM random_test);
SET @min := (SELECT MAX(HEX(LEFT(id, 6))) FROM random_test);

SELECT id 
FROM(
      SELECT id
      FROM (SELECT FLOOR(RAND() *  (@max - @min) + @min) AS start FROM random_test) AS init
      JOIN random_test y
      WHERE HEX(LEFT(y.id, 6)) > init.start OR HEX(LEFT(y.id, 6)) < init.start
      ORDER BY y.id
      LIMIT 50          
) z 
ORDER BY RAND()
LIMIT 2 
```

**Comment by ramsey** [comment]
@jckeen Depending on the type of UUID you're using, I would not recommend using the first _x_ characters of a UUID to determine identity. In a version 1 UUID, for example, these characters are going to be very similar and even cause collisions. In a version 4 UUID, it might be okay to do this (though the chance for collision goes way up, since you're limiting the amount of randomness you have), and your application will have a dependency on always using version 4 UUIDs, so you'll need to validate the UUID version before inserting into the database.
