### ISSUE TITLE
Document (in composer.json) ext-ctype dependency

### ISSUE THREAD

**Issue by iansltx** [ramsey/uuid#142]
With a more minimal PHP install (e.g. Alpine packages), ctype isn't included by default, but it's required for DefaultTimeGenerator, see https://github.com/ramsey/uuid/search?utf8=%E2%9C%93&q=ctype

All well and good, but this should probably fail on composer install rather than waiting 'til runtime.

Alternately, preg_match on /^[0-9A-F]+$/i should do the trick without requiring ctype, but I have a feeling (haven't benchmarked) the ctype method is faster, and most envs will have the extension anyway.

**Comment by ramsey** [comment]
Thanks for catching this, @iansltx. I'll add ext-ctype as a dependency.

**Comment by ramsey** [comment]
A polyfill has been added for the Ctype functions, and I've added `ext-ctype` as a suggested extension in `composer.json` here: 735eb7e3c9a3adb3f6764677e96aa16fdd33661f
