### ISSUE TITLE
Can this library parse UUID's?

### ISSUE THREAD

**Issue by kevinburke** [ramsey/uuid#145]
I'm looking for a tool that can take a string and tell me whether it's a valid UUID or not, and if valid, give me the methods that you have here. I checked the README and the Cookbook and didn't find any examples.

**Comment by ramsey** [comment]
Most certainly. The wiki documentation is lacking right now. I hope to remedy this soon.

There are a couple of ways to accomplish this. One is simply by using the `fromString()` static method and wrapping it in a try/catch block. If it's not a valid UUID, it'll throw an `InvalidArgumentException`.

``` php
<?php
require_once 'vendor/autoload.php';

use Ramsey\Uuid\Uuid;;

$strings = [
    'a6bae20c-b1c5-11e6-80f5-76304dec7eb7',
    'foobar',
    'cd8e136e-45a9-4aa2-ab83-e96cb5365755',
];

foreach ($strings as $str) {
    try {
        $uuid = Uuid::fromString($str);
        printf("Found version %d UUID: %s\n", $uuid->getVersion(), $uuid);
    } catch (InvalidArgumentException $e) {
        printf("The string %s is not a UUID.\n", $str);
    }
}
```

This script produces the following output:

```
Found version 1 UUID: a6bae20c-b1c5-11e6-80f5-76304dec7eb7
The string foobar is not a UUID.
Found version 4 UUID: cd8e136e-45a9-4aa2-ab83-e96cb5365755
```

Another option is to use the static `isValid()` method, like this:

``` php
foreach ($strings as $str) {
    if (Uuid::isValid($str)) {
        printf("%s is a valid UUID.\n", $str);
    } else {
        printf("%s is not a valid UUID.\n", $str);
    }
}
```

I hope this helps. Let me know if you have any other questions.

**Comment by pawaroti** [comment]
There is alsow some issue with validation, ie. string "c93eaf02-b607-4433-8441-b0fa7c8f5fc9}}" is treated as valid UUID

**Comment by ramsey** [comment]
@pawaroti This is because the following are valid UUID strings:

```
c93eaf02-b607-4433-8441-b0fa7c8f5fc9
{c93eaf02-b607-4433-8441-b0fa7c8f5fc9}
urn:uuid:c93eaf02-b607-4433-8441-b0fa7c8f5fc9
```

The `isValid()` method [strips these out before validating the UUID string](https://github.com/ramsey/uuid/blob/master/src/Uuid.php#L618-L637).

``` php
$uuid = str_replace(array('urn:', 'uuid:', '{', '}'), '', $uuid);
```
