### ISSUE TITLE
uuid1 error from Moontoast/Math convertFromBase10

### ISSUE THREAD

**Issue by wohenbushuang** [ramsey/uuid#150]
I tried to use uuid1() this week and always get results like `00000000-0000-1100-b503-1a5d60bf5ab9`, where only `b503` part will change by time. 

After debug I found that all other parts are fine except class `BigNumber` function `public static function convertFromBase10($number, $toBase)` in `Moontoast/Math/BigNumber.php` line#638-#662:

```PHP
    /**
     * Converts a base-10 number to an arbitrary base (from 2 to 36)
     *
     * @param string|int $number The number to convert
     * @param int $toBase The base to convert $number to
     * @return string
     * @throws \InvalidArgumentException if $toBase is outside the range 2 to 36
     */
    public static function convertFromBase10($number, $toBase)
    {
        if ($toBase < 2 || $toBase > 36) {
            throw new \InvalidArgumentException("Invalid `to base' ({$toBase})");
        }

        $bn = new self($number);
        $number = $bn->abs()->getValue();
        $digits = '0123456789abcdefghijklmnopqrstuvwxyz';
        $outNumber = '';
        $returnDigitCount = 0;

        while (bcdiv($number, bcpow($toBase, (string) $returnDigitCount)) > ($toBase - 1)) {
            $returnDigitCount++;
        }

        for ($i = $returnDigitCount; $i >= 0; $i--) {
            $pow = bcpow($toBase, (string) $i);
            $c = bcdiv($number, $pow);
            $number = bcsub($number, bcmul($c, $pow));
            $outNumber .= $digits[(int) $c];
        }

        return $outNumber;
    }
```

The returned `$outNumber` is always 100000000000000 while `$number` changes everytime. The problem is that `bcdiv` will return result with decimal part, so it should be:
```PHP
$c = bcdiv($number, $pow, 0);
```
in line#656 to emit decimal part.

However I don't know how to deal with this with composer, because Moontoast/Math seems no longer maintained.....

Environment: Windows8x64 WAMP3.0.6x64 PHP5.6.25
composer.json:
```JSON
    "require": {
        "ramsey/uuid": "^3.5",
        "moontoast/math": "^1.1"
    },
    "minimum-stability": "dev"
```
Without Moontoast/Math it will throw `UnsatisfiedDependencyException`

**Comment by ramsey** [comment]
I'm still maintaining moontoast/math here: https://github.com/ramsey/moontoast-math. This is the repository Packagist (and Composer) uses when pulling in the moontoast/math dependency, so if you have any pull requests to make against it, that's where you can submit them.

That said, I'll get a Windows 8 VM and try to take a look at this soon. It might be something about the PHP build you're using on Windows 8 that's causing a previously unreported bug in moontoast/math to crop up.

**Comment by wohenbushuang** [comment]
@ramsey I think that this problem is independent with the environment, [example in php.net](http://php.net/manual/en/function.bcdiv.php) has shown that `bcdiv` will have decimal part.

The best way is to use `$c = bcdiv($number, $pow, 0);` in `BigNumber.php`, and I found a temporary way in php.net doc, that is to call `bcscale(0);` before `Uuid::uuid1()`, and this way worked in my environment.

**Comment by ramsey** [comment]
According to php.net, the default for the third parameter of `bcdiv()` is `0`:

```
string bcdiv ( string $left_operand , string $right_operand [, int $scale = 0 ] )
```

However, if the `$scale` is not provided and it was set earlier with `bcscale()`, it will default to the globally set scale. Are you setting the scale with `bcscale()` elsewhere in your application?

I agree that the best way to avoid inheriting a globally set scale is to set it explicitly in moontoast/math with `$c = bcdiv($number, $pow, 0);`. I'm just trying to understand why this issue occurs for you but no one else. Understanding that will help me to help others in the future with similar problems.

**Comment by wohenbushuang** [comment]
Well, I require this package inside my plugin folder of OctoberCMS, hope that this will help you. For me, I can't find any clue that OctoberCMS has changed the `scale` by global searching.

**Comment by juliusstoerrle** [comment]
I got the same issue on Windows10 64x.
When I use the PhpTimeConverter, the first part is changing, but the rest still is the same as described by wohenbushuang.

**Comment by ramsey** [comment]
I've just released 1.1.2 of moontoast/math, which should fix this issue. Please update:

    composer update moontoast/math

Let me know if this resolves the issue. Thanks!

**Comment by juliusstoerrle** [comment]
Yes, now its working properly!

**Comment by ramsey** [comment]
Good to hear. Thanks for the help!
