### ISSUE TITLE
Extract timestamp from UUIDv1

### ISSUE THREAD

**Issue by hi2u** [ramsey/uuid#152]
Given an already-generated UUIDv1, is there a way to pass this to the library and have its timestamp extracted and returned?

There seems to be some libraries in Python, Java etc that can do this.  Is it possible with this PHP library?

**Comment by ramsey** [comment]
Certainly! The Python and Java libraries were inspirations for this library. :-)

The `Uuid` class has a static `fromString()` method that accepts a UUID string and returns a `Ramsey\Uuid\Uuid` object from that string. You may then use the `getDateTime()` with version 1 UUIDs to get a [PHP DateTime object](http://php.net/datetime).

``` php
use Ramsey\Uuid\Uuid;

$uuidA = Uuid::fromString('67991cd2-e696-11e6-bf01-fe55135034f3');

echo 'Version: ' . $uuidA->getVersion() . "\n";
echo 'Time: ' . $uuidA->getDateTime()->format('r') . "\n";
```

The output for this example is:

```
Version: 1
Time: Mon, 30 Jan 2017 02:47:14 +0000
```

If you try to use `getDateTime()` on a UUID that isn't a version 1 (time-based) UUID, then ramsey-uuid will throw the exception `Ramsey\Uuid\Exception\UnsupportedOperationException`.

For example, if using the same code above with the string UUID "dec3781d-fa72-4d83-b00b-c1ae6b3b49bc," you'll see this output:

```
Version: 4
PHP Fatal error:  Uncaught Ramsey\Uuid\Exception\UnsupportedOperationException: Not a time-based UUID
```

You can use a try/catch block to catch the exception, if you need to do so.

**Comment by hi2u** [comment]
Awesome!  Thanks for the detailed instructions!

I gave it a test on cab7b37c-e683-11e6-b115-e89a8f13849e (generated at unix timestamp 1485736439.284019), and added "u" (microseconds) to the output format, but it just showed "000000".

So it looks like it only has granularity down to the whole second?  My understanding is that UUIDv1 supports down to 0.0000001 seconds (100 nano).

Would it be possible for the library to include microseconds in the DateTime object?

**Comment by ramsey** [comment]
Take a look at #90 and #93. The problem is that this library still supports PHP 5.4. Version 4 of this library will be either 5.6+ or 7.0+ (I'm leaning towards 7.0+), in which case I'll be able to create the DateTime object with microseconds.

**Comment by hi2u** [comment]
Ok thanks for the response.

Although could this not just be done for PHP versions that support it?  i.e...

```php
if (defined('PHP_VERSION_ID') AND PHP_VERSION_ID > 502020)
{
    // new DateTime with microtime
}
else
{
    // new DateTime without microtime
}
```

I can't really imagine that causing issues for anyone?

Or alternatively if you really want it to stay consistent, just add a new method called something like `getDateTimeWithMicroseconds()` ... then it will be consistent forever instead of changing in a future version.

**Comment by ramsey** [comment]
Those are good ideas. I'll consider them. Thanks!

**Comment by friek108** [comment]
Great, but what about the other way around - ie. generate a UUID based on a historical time? (I know there is the `FixedTimeProvider` class but can't work out after a lot of searching how to use this.

**Comment by ramsey** [comment]
@friek108, take a look at my comment here and see if it helps steer you in the right direction. I need to add this example to the wiki. 😁

https://github.com/ramsey/uuid-doctrine/issues/39

**Comment by ramsey** [comment]
By the way, you don’t have to do the `OrderedTimeCodec` part of that example. Let me know if you need any help working it out and I can simplify the example here.

**Comment by ramsey** [comment]
Please see version 4.0.0-alpha1. The `getDateTime()` method now returns a `\DateTimeInterface` instance that includes the microseconds.
