### ISSUE TITLE
"Could not gather sufficient random data" random_bytes(), docker and php7

### ISSUE THREAD

**Issue by WillSkates** [ramsey/uuid#156]
Hi everyone,

This is a quick notice for anyone that has the above issue ("Could not gather sufficient random data") with docker with random_bytes and docker.

There seems to be a general issue with php 7.x and 7.1.x at the moment where most people cannot use ```random_bytes();``` within a docker container. The reason is that the random_bytes() implementation that ships with php7 calls a system function ```getrandom()``` [more details here](http://man7.org/linux/man-pages/man2/getrandom.2.html).

The ```getrandom()``` system function isn't available to php when it is compiled against one linux kernel and then used with another. This is frequently but not exclusively true with docker because we use images that were compiled on the hub or from a package manager. A lot of the time we tend not to compile php ourselves.

It looks like there will be a fix in the next release version. For now try downgrading to 7.0.15 or 7.1.1.

[Bug](https://bugs.php.net/bug.php?id=74105)
[Cause](https://github.com/php/php-src/commit/14c72cc5824d5fa472b79b7216a01be0918ccc5d)
[Fix](https://github.com/php/php-src/commit/513582814b0ca82d81eb6b98897d745e0f0eebf5)

Cheers,
Will

P.s. Apologies if the above information is incorrect. My [source](https://fabian-martin.name/blog/2017/02/19/php-7-0-could-not-gather-sufficient-random-data/) is written in german and I'm not a fluent german speaker.

**Comment by ramsey** [comment]
Thanks for the report. I'll leave this open for a while with the "informational" label on it, in case anyone comes here looking for an answer to this issue.

**Comment by WillSkates** [comment]
@ramsey Thanks hopefully it will save people some time. I added some text to describe a temporary solution.
