### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by iainmckay** [ramsey/uuid#159]
We were profiling and noticed that out of our process we're using a higher than expected amount of memory generating UUID's (version 4). The profiler pointed out that `sprintf` was the cause, we tracked it to `UuidFactory::uuidFromHashedName`.

I did a quick test and replaced `sprintf` with `str_pad` and `dechex`, on 500,000 iterations we saw a considerable difference.

I've attached my test [here](https://gist.github.com/iainmckay/60852c9518e7d26db588d4c9909de136) to demonstrate the memory difference and perhaps someone can poke a hole and say we're being silly.

The results when we run locally on PHP 7.0 is:

```
$ php test.php 
sprintf: time=0.9005069732666 mem=176781392 memreal=176164864
str_pad: time=0.47726893424988 mem=32781392 memreal=33558528
```

This particular part of our system is asking for several hundred thousand UUID's and this function is using `sprintf` twice so this affects our memory budget quite a bit.

**Comment by ramsey** [comment]
That's a great catch and a quick win to save some memory! Would you like to put together a PR for this and submit it? I don't mind doing it, but I want to give you the option to get the commit credit. 😁

**Comment by iainmckay** [comment]
Thanks, I've created a PR.

**Comment by ramsey** [comment]
Thanks!
