### ISSUE TITLE
Use custom exception instead of InvalidArgumentException

### ISSUE THREAD

**Issue by garak** [ramsey/uuid#161]
The current parsing of UUID is throwing an `InvalidArgumentException`, that is too generic IMHO.
See [StringCodec](https://github.com/ramsey/uuid/blob/8d2bab3c17c6325551ffd5562105a95e21c049de/src/Codec/StringCodec.php#L142).

Since I'm using UUIDs in web application URLs, I can't be sure that I'll get valid ones. So, when I transform the  UUID string I'm getting from URL into an UUID object, by calling `Uuid::fromString()`, I'd like to get a possible specific exception, something like `InvalidUuidException`.

This change should cause no BC break, if `InvalidUuidException` extends  extend `InvalidArgumentException`

**Comment by ramsey** [comment]
This sounds good to me. Would you like to open a PR to get the commit credit for it? Otherwise, I don't mind doing the work.

**Comment by garak** [comment]
Of course, I'll do it tomorrow

**Comment by garak** [comment]
Great. I look forward for a tag. Thanks.

**Comment by ramsey** [comment]
Thanks for the reminder. Just tagged 3.6.0. :smile:
