### ISSUE TITLE
Uuid::isValid() returns false for hex strings

### ISSUE THREAD

**Issue by charliekassel** [ramsey/uuid#167]
I'm trying to use uuid's with the getHex method but this fails the isValid regex test.

**Comment by ramsey** [comment]
Can you post some example code of what you're trying to do? Thanks!

**Comment by charliekassel** [comment]
I'm trying to use uuid's without hyphens so using the `getHex` method to return the id. On receiving an id in a controller via a route/url I'm just testing validity before doing anything further.

```
if (!Uuid::isValid($id)) {
   throw new InvalidArgumentException('Bad id');
}
```

I'm using it with `doctrine-uuid` and notice that this also uses the `isValid` method in the `convertToDatabaseValue` method.

Changing this method to use the fromString method works but seems pretty inefficient and looks nasty:
```
/**
     * {@inheritdoc}
     *
     * @param Uuid|null                                 $value
     * @param \Doctrine\DBAL\Platforms\AbstractPlatform $platform
     */
    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        if (empty($value)) {
            return null;
        }

        try {
            return Uuid::fromString($value)->toString();
        } catch (\InvalidArgumentException $e) {
            throw ConversionException::conversionFailed($value, self::NAME);
        }

        if ($value instanceof Uuid || Uuid::isValid($value)) {
            return (string) $value;
        }

        throw ConversionException::conversionFailed($value, static::NAME);
    }
```

Do you have a recommendation for how to use the uuid with Doctrine without hyphens? (a PM request...)

**Comment by ramsey** [comment]
The problem is that the string representation of a UUID includes the dashes. Otherwise, there's no way to discern the difference between a UUID and a 32-character hexadecimal string, which just looks like an MD5 hash. I want to be careful about validating that any 32-character hexadecimal string is a valid UUID.

I'll give this some thought and get back to you.

**Comment by ramsey** [comment]
Are you using the [ramsey/uuid-doctrine field type](https://github.com/ramsey/uuid-doctrine), or are you creating your own mapping?

**Comment by charliekassel** [comment]
I am using that package yes.

**Comment by charliekassel** [comment]
The method I refer to earlier is `UuidType::convertToDatabaseValue()`

**Comment by frankvice** [comment]
is it possible to use "_" instead of "-" ?

**Comment by ramsey** [comment]
Underscores are not valid in the string representation of UUIDs. Only dashes.

**Comment by charliekassel** [comment]
Potentially a naive idea but here's a PR - https://github.com/ramsey/uuid/pull/168

**Comment by ramsey** [comment]
My recommendation for storing UUIDs without dashes and converting them back into `Ramsey\Uuid\Uuid` objects is to create a custom Doctrine field type. You could base it off the work in ramsey/uuid-doctrine and use `getHex()` when storing the string to the DB and `fromString()` to validate the hexadecimal string as a UUID when you retrieve the value from the DB.
