### ISSUE TITLE
Multicast bit not set for randomly-generated network nodes in v1

### ISSUE THREAD

**Issue by crazytonyi** [ramsey/uuid#171]
Not sure how to tie an issue to a PR, but figured it is preferred that peanut-gallery PRs have a related issue. As noted in PR #170:

Per RFC 4122, 4.6:

>  For systems with no IEEE address, a randomly or pseudo-randomly generated value may be used; see Section 4.5.  The multicast bit must be set in such addresses, in order that they will never conflict with addresses obtained from network cards.

and 4.5:

> A better solution is to obtain a 47-bit cryptographic quality random number and use it as the low 47 bits of the node ID, with the least significant bit of the first octet of the node ID set to one.  This bit is the unicast/multicast bit, which will never be set in IEEE 802 addresses obtained from network cards.  Hence, there can never be a conflict between UUIDs generated by machines with and without network cards.  (Recall that the IEEE 802 spec talks about transmission order, which is the opposite of the in-memory representation that is discussed in this document.)

> For compatibility with earlier specifications, note that this document uses the unicast/multicast bit, instead of the arguably more correct local/global bit.

Thus, the Least Significant Bit of the randomly-generated node ID should be set to 1 to indicate that it is a randomly-generated node ID.

Proposed change is to flip the least-significant bit of the second randomly-generated number via inclusive OR bitwise operator.

**Comment by ramsey** [comment]
Mentioning an issued in a PR (or vice versa) automatically “links” them, though creating an issue wasn’t necessary for this project.

Thanks for the PR! I’m out of town for a family issue right now, and I’ll take a look next week when I get back.

Cheers!
