### ISSUE TITLE
Is there a UUID validator available ?

### ISSUE THREAD

**Issue by Yamakasi** [ramsey/uuid#178]
Is it possible with this library to check if a UUID is a valid one when you get it from a database or where it might come from ?

**Comment by mhujer** [comment]
You can call it like this:

`$isValid = Uuid::isValid($uuidFromSomewhere)`

**Comment by Yamakasi** [comment]
Thanks.

But we cannot test for version ?

**Comment by mhujer** [comment]
Probably not directly, but I think you can create your own validator like this:

1) check that the given string is a valid UUID using the code I mentioned above
2) and then use `Uuid::fromString($uuidFromSomewhere)->getVersion()` to get the version of the specific UUID

**Comment by Yamakasi** [comment]
Thanks, that is a great idea!

Maybe Ramsey can turn it into it's own function.

**Comment by ramsey** [comment]
You can check the version by creating a UUID object, and calling `getVersion()`:

``` php
try {
    $uuid = Uuid::fromString($stringUuid);

    if ($uuid->getVersion() === Uuid::UUID_TYPE_RANDOM) {
        // It's a v4 UUID
    }
} catch (InvalidUuidStringException $e) {
    // UUID is not valid
}
```

In version 4 of the library, I'm considering introducing subclasses for each UUID version, so you could use an `instanceof Uuid5` check, for example.

**Comment by Yamakasi** [comment]
Would be great! Thanks.

**Comment by ramsey** [comment]
Please see version 4.0.0-alpha1. This version includes a validator for RFC 4122 variant UUIDs. It is not the default validator, but you may swap out default validator used by the factory with this one, if you like.

```
$validator = new \Ramsey\Uuid\Rfc4122\Validator();

if ($validator->validate('8ed543d7-a6ad-4746-8c11-7b27437c0d38')) {
    echo 'The UUID is valid!';
}
```

Also, notice that UUIDs created in version 4.0.0-alpha1 will be sub-classed appropriately:

``` php
use Ramsey\Uuid\Uuid;

$uuid1 = Uuid::uuid1();
$uuid2 = Uuid::uuid2(Uuid::DCE_DOMAIN_PERSON);
$uuid3 = Uuid::uuid3(Uuid::NAMESPACE_URL, 'https://example.com');
$uuid4 = Uuid::uuid4();
$uuid5 = Uuid::uuid5(Uuid::NAMESPACE_URL, 'https://example.com');

if ($uuid1 instanceof \Ramsey\Uuid\Rfc4122\UuidV1) {
    echo "\$uuid1 is an instance of UuidV1\n";
}

if ($uuid2 instanceof \Ramsey\Uuid\Rfc4122\UuidV2) {
    echo "\$uuid2 is an instance of UuidV2\n";
}

if ($uuid3 instanceof \Ramsey\Uuid\Rfc4122\UuidV3) {
    echo "\$uuid3 is an instance of UuidV3\n";
}

if ($uuid4 instanceof \Ramsey\Uuid\Rfc4122\UuidV4) {
    echo "\$uuid4 is an instance of UuidV4\n";
}

if ($uuid5 instanceof \Ramsey\Uuid\Rfc4122\UuidV5) {
    echo "\$uuid5 is an instance of UuidV5\n";
}
```
