### ISSUE TITLE
Improvements to (the tests for) the SystemNodeProvider class.

### ISSUE THREAD

**Issue by Potherca** [ramsey/uuid#187]
Prompted by #185 (written by my friend and colleague @mjrider) I would like to suggest a few improvements to the `Ramsey\Uuid\Provider\Node\SystemNodeProvider` class and the test it comes with:

1. The SystemNodeProviderTest mocks (part of) the class it is testing. [This is a testing anti-pattern](http://wiki.c2.com/?SubclassToTestAntiPattern). The main reason seems to be that, instead of changing the code to be testable, the test was changed (for the worse).
I would suggest [this change](https://github.com/potherca-contrib/uuid/compare/master...07228a3b3751018399a1679fca4d3cec04e20601) to fix that. (Taking it [one step further](https://github.com/potherca-contrib/uuid/compare/2bf98b246f6ff76730cb394dae7d3a50a6c3c4b5...ddd340a9241ed0cdf83b155d60a54b7e2aa37783) might be a bit too much.)
2. <del>All tests have `@runInSeparateProcess` and `@preserveGlobalState disabled` annotations. The only reason for this seems to be the use of a static variable in the `getNode` function.
By [replacing the static variable with a class variable](https://github.com/potherca-contrib/uuid/compare/07228a3b3751018399a1679fca4d3cec04e20601...2bf98b246f6ff76730cb394dae7d3a50a6c3c4b5) this issue can easily be resolved.</del>
The static variable in the `SystemNodeProvider::getNode()` function should be class-level, not function-level

The code I link to is a suggestion, if there are any reasons I have missed, the code can be changed accordingly.

Also, as a matter of priority, I'll wait with opening a PR for this until the changes in #185 have been merged to master, as that code is in the system and these changes are more for the benefit of the tests.

---

**Edit:** After a discussion with @mjrider I understand that having `$node` be static (i.e. shared across several instances of the same class) is desirable for performance by avoiding calling the functionality more than once. I have updated my suggestion to change the level of static variable.

**Comment by ramsey** [comment]
What you've described here sounds good to me. Even the "taking it one step further" with the constructor is good, IMO. If you open this as a PR, I'll accept it. Thanks!

**Comment by ramsey** [comment]
@Potherca, are you still interested in working on this?

**Comment by Potherca** [comment]
Yup, thanks for the reminder! I was waiting for #185 and it slipped further down my todo list over the holidays.

I've already got work for this ready on my fork, I'll take a look at it and open a PR this coming week.

**Comment by Potherca** [comment]
The code has changed somewhat since I opened this issue and there seem to be very few failure-scenario tests.

Because of this, I've decided against the `construct` route in favour of more accurately mocking the native calls. 

Work is underway, I hope to open a PR for this soonish.

**Comment by Potherca** [comment]
As the accompanying pull-request has been merged I am closing this issue.
