### ISSUE TITLE
Works as primary key with Doctrine ?

### ISSUE THREAD

**Issue by tyx** [ramsey/uuid#19]
Hi !

Great job with this lib. Exactly what we need. Thanks.

We just found a small issue and I just want to be sure I use it in the right way before writing any PR.

If I put my primary key in my doctrine mapping with your custom type, it works pretty well on persist operation. But on find method I get :
`Warning: Illegal offset type in /Users/Tim/www/cqrs-afsy/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php line 2480
`

I understand the problem Doctrine met : 
`$idHash = isset($class->associationMappings[$class->identifier[0]])
                ? $data[$class->associationMappings[$class->identifier[0]]['joinColumns'][0]['name']]
                : $data[$class->identifier[0]];`

with type `uuid` $idHash will be an object and then doctrine try to use it as array key on line 2480.

Have I missed anything or should I propose PR to doctrine ? Anyone use this lib on Doctrine without these kinds of problem ?

**Comment by stefanotorresi** [comment]
ICYMI this has been fixed upstream with https://github.com/doctrine/doctrine2/pull/1336

**Comment by tyx** [comment]
Thank you @stefanotorresi ! Looks great
