### ISSUE TITLE
namespace Rhumsaa\Uuid

### ISSUE THREAD

**Issue by johnmoney** [ramsey/uuid#198]
Works with:

`use Rhumsaa\Uuid\Uuid;
use Rhumsaa\Uuid\Exception\UnsatisfiedDependencyException;
`

**Comment by ramsey** [comment]
The `Rhumsaa` namespace was discontinued in the 3.x series. Versions prior to 3.0.0 use `Rhumsaa`. 3.0.0 and later use `Ramsey`.

Did you have a question or problem using the namespace?

**Comment by johnmoney** [comment]
Yeah my bad, I quickly read the readme and used

composer require ramsey/uuid=^2.9

**Comment by ramsey** [comment]
No worries. Let me know if you have any suggestions foe improving the README so that it’s clearer on this issue. The correct way to install is to use:

```
composer require ramsey/uuid
```

That will give you the latest version in the 3.x series.

Cheers!
