### ISSUE TITLE
Uniformly distributed UUID (UUID COMB)

### ISSUE THREAD

**Issue by marijn** [ramsey/uuid#2]
One of the drawbacks of using a `UUID` as identifier in a RDBMS is that they are not uniformly distributed. To prevent a decrease in performance it is possible to create a different kind of `UUID` which contains a timestamp part with a high time resolution (ms).

Would you be open to a PR that would add this functionality?

**Comment by ramsey** [comment]
Implemented in #43. Closing this out.
