### ISSUE TITLE
Fatal error: Out of memory (allocated 46137344) (tried to allocate 20480 bytes)

### ISSUE THREAD

**Issue by kjhatis** [ramsey/uuid#202]
Fatal error: Out of memory (allocated 46137344) (tried to allocate 20480 bytes) in D:\xampp\htdocs\XXXXXX\vendor\ramsey\uuid\src\Codec\StringCodec.php on line 57

``

class UserModel extends Model {

    protected $fillable = ['uuid', 'name', 'email', 'password', 'activated'];
    protected $table = 'users';
    public $timestamps = false;
    protected $dataFormats = 'u';

    public static function create($data) {
        try {
            $uuid4 = Uuid::uuid4();
            return self::create([
                        'uuid' => $uuid4->toString(),
                        'name' => isset($data['name']) ? $data['name'] : '',
                        'email' => isset($data['email']) ? $data['email'] : throwException("Email Is Required!"),
                        'password' => isset($data['password']) ? $data['password'] : throwException("Password is Required!")  
            ]);
        } catch (\Exception $e) {
            //Log::error($e->getTrace());
            return $e->getTrace();
        }
    }

``

Not sure Where is the mistake.

**Comment by kjhatis** [comment]
Fatal error: Out of memory (allocated 767557632) (tried to allocate 262144 bytes) in D:\xampp\htdocs\LearningGPS\vendor\ramsey\uuid\src\Builder\DegradedUuidBuilder.php on line 51

**Comment by tomzx** [comment]
Most likely you have too much memory allocated elsewhere, and this is just where your program crashes. It's unlikely that uuid is the issue here.

**Comment by ramsey** [comment]
Is the script that's running when you see this error using a lot of memory for some other processes before it gets to this point?

**Comment by kaphert** [comment]
Your code contains an infinite loop. You are calling `self::create()` instead of`parent::create()`.

**Comment by ramsey** [comment]
@kaphert Since it's a static method, should it be `static::create()` instead?

**Comment by kaphert** [comment]
This issue is not related to the uuid library. 

The code should be:
```php
public static function create($data) {
    try {
        $uuid4 = Uuid::uuid4();
        return parent::create([
                    'uuid' => $uuid4->toString(),
                    'name' => isset($data['name']) ? $data['name'] : '',
                    'email' => isset($data['email']) ? $data['email'] : throwException("Email Is Required!"),
                    'password' => isset($data['password']) ? $data['password'] : throwException("Password is Required!")  
        ]);
    } catch (\Exception $e) {
        //Log::error($e->getTrace());
        return $e->getTrace();
    }
}
```

This is part of a Laravel Eloquent model. I would not recommend doing value checks and assign UUID but that is another issue.

**Comment by ramsey** [comment]
Ah. I see. I wasn't paying attention to the fact that the code override's the parent's static `create()` method, so even using `static::create()` would be problematic, so it must be `parent::create()`.

@kjhatis, please confirm that this fixes your issue.

Thanks, @kaphert!
