### ISSUE TITLE
Warning after update to v3.7.2

### ISSUE THREAD

**Issue by forgie1** [ramsey/uuid#203]
On linux system we use uuid_binary is after update to v3.7.2 happening this:

After call:
RUuid\Uuid::uuid1()->getBytes();

It ends up in the: SystemNodeProvider.php:94 :
```
$macs = array_map(
    'file_get_contents',
    glob('/sys/class/net/*/address', GLOB_NOSORT)
 );

```

with warning:
`array_map(): Argument #2 should be an array`

May it be connected with the changes in the v3.7.2 ?
After rollback to v3.7.1 there are not warning any more.

**Comment by ramsey** [comment]
Thanks for reporting this. What Linux distribution are you using? I’ll get a bug fix out for this ASAP.

**Comment by forgie1** [comment]
I use Debian 8 jessie.

**Comment by ramsey** [comment]
Is `/sys/class/net/` available on your system, and, if so, is it readable by all?

**Comment by ramsey** [comment]
Also please provide the PHP version and whether you're running this in the context of a web server (i.e. what user is running the script)?

**Comment by ramsey** [comment]
One final thing, can you log in through the terminal to the server where you experienced this problem and execute the following:

``` shell
php -r "var_export(glob('/sys/class/net/*/address', GLOB_NOSORT));"
```

It should print out something that looks like this:

```
array (
  0 => '/sys/class/net/eth0/address',
  1 => '/sys/class/net/lo/address',
  2 => '/sys/class/net/tunl0/address',
  3 => '/sys/class/net/ip6tnl0/address',
)
```

I did this on Debian Jessie in a Docker container, and it works for me, but there could be something different about your environment that's causing `glob()` to produce a `false` response (rather than an array), which would indicate some sort of error.

I have a way to work around this, but I'd like to be able to reproduce it, too, so I know under what conditions to expect it and so I can write a better test.

Thanks!

**Comment by forgie1** [comment]
I use PHP 7.2. run by FPM under apache.

The rest of questins I will reply soon, I must find out, I have limitted CLI access and I myself do not have as chrooted user access to  `/sys/class/net/`.

Command: `php -r "var_export(glob('/sys/class/net/*/address', GLOB_NOSORT));"` returns empty array:
```
array (
)
```

I will reply soon with more detail answers.

**Comment by ramsey** [comment]
I was able to implement a fix for this (it'll be forthcoming in version 3.7.3 shortly).

However, I'd still like to understand the conditions that would cause `glob()` to return something other than an array. If it can't find the files, it should be an empty array, as you've shown, and that should be fine for `array_map()`. However, the PHP docs state:

> Returns an array containing the matched files/directories, an empty array if no file matched or FALSE on error.
>
> **Note:**
> On some systems it is impossible to distinguish between empty match and an error.

It sounds like we might be hitting some condition that results in being unable to distinguish between an empty match and an error, but I can't be sure.

Thanks again for the bug report!

**Comment by forgie1** [comment]
Thanks for the fix.
The reason was the path was not allowed in  open_basedir. Now we have allowed this path in  open_basedir and it works fine. So setup of ` open_basedir` was the cause of the problem.

**Comment by ramsey** [comment]
Good to know. Thanks for investigating.

I'm just waiting on Travis CI to sort out their job queue before tagging the release: https://www.traviscistatus.com/incidents/c1s4dlyxd4lf

**Comment by ComradePashka** [comment]
Hello!

Seems that I got issue quite related once again:
composer.json:
```
"ramsey/uuid": "^4.1"
```
php version: 8.0.2
shared hosting at Dreamhost:
```
uname -a
Linux culver 4.14.117-grsec-grsec+ #1 SMP Fri May 10 17:15:47 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux)
```

here is response from command:
```
php -r "var_export(glob('/sys/class/net/*/address', GLOB_NOSORT));"
array (
  0 => '/sys/class/net/bond0/address',
  1 => '/sys/class/net/phy1/address',
  2 => '/sys/class/net/eth1/address',
  3 => '/sys/class/net/sit0/address',
  4 => '/sys/class/net/lo/address',
  5 => '/sys/class/net/phy0/address',
  6 => '/sys/class/net/teql0/address',
)
```

and lumen (laravel-based php framework) begining of error log file:
```
[2021-07-02 10:36:48] production.ERROR: file_get_contents(/sys/class/net/bond0/address): Failed to open stream: Permission denied {"exception":"[object] (ErrorException(code: 0): file_get_contents(/sys/class/net/bond0/address): Failed to
 open stream: Permission denied at /home/gigqo/gigqo-api/vendor/ramsey/uuid/src/Provider/Node/SystemNodeProvider.php:156)
[stacktrace]
#0 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(2, 'file_get_conten...', '/home/gigqo/gig...', 156)
#1 /home/gigqo/gigqo-api/vendor/ramsey/uuid/src/Provider/Node/SystemNodeProvider.php(156): file_get_contents('/sys/class/net/...')
```

they specific place to customize php settings it's insie ~/.php/x.x/phprc file, where x.x is corresponding php version, after adding open_basedir with path to /sys/class/net/ error gone
