### ISSUE TITLE
fromString($uuid) return false on wrong string ?

### ISSUE THREAD

**Issue by Yamakasi** [ramsey/uuid#216]
Is it an idea to return a false when the string you insert is not a valid hex and cannot be turned into a valid full UUID ?

**Comment by ramsey** [comment]
If the string is not a valid UUID, the library throws an exception, which you can catch:

``` php
try {
    $uuid = Ramsey\Uuid\Uuid::fromString('foobar');
} catch (Ramsey\Uuid\Exception\InvalidUuidStringException $e) {
    // The string wasn't a valid UUID, so do something else.
}
```

**Comment by Yamakasi** [comment]
Thanks, but I don't want to do too much try/catch when not needed. it seems you can check for empty() or is_object() as well.

**Comment by ramsey** [comment]
Changing the behavior of the `fromString()` method would be a major backwards compatibility break. That’s a change I’m not willing to introduce. Using try/catch blocks is the recommended approach. If you don’t want to use a lot of them, you can create a single method or function to encapsulate it for you.

**Comment by Yamakasi** [comment]
Also a good suggestion. But you would have a variable set for the class you load and the exception you catch to keep it flexible ?

Was my empty() or is_object() check also valid to you ?

**Comment by ramsey** [comment]
There are multiple ways to accomplish what you want to do without making any changes to the library. Here are some examples. I hope this helps.

``` php
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\Exception\InvalidUuidStringException;

function myUuidFromString1($string) {
    try {
        return Uuid::fromString($string);
    } catch (InvalidUuidStringException $e) {
        return false;
    }
}

function myUuidFromString2($string) {
    if (Uuid::isValid($string)) {
        return Uuid::fromString($string);
    }
    return false;
}

$testStrings = [
    'f88bec2f-353b-4207-9ec6-1ac69d84b1ed',
    'foo',
    '9febecd0-2b24-11e8-b467-0ed5f89f718b',
    'bar',
];

foreach ($testStrings as $string) {
    $uuid = myUuidFromString1($string);
    if (empty($uuid)) {
        echo "{$string} is not a valid UUID\n";
    } else {
        echo (string) $uuid . " is a valid UUID\n";
    }
}

foreach ($testStrings as $string) {
    $uuid = myUuidFromString2($string);
    if ($uuid instanceof Uuid) {
        echo (string) $uuid . " is a valid UUID\n";
    } else {
        echo "{$string} is not a valid UUID\n";
    }
}
```
