### ISSUE TITLE
Using DateTimeInterface instead of DateTime

### ISSUE THREAD

**Issue by garak** [ramsey/uuid#222]
I see that `getDateTime` method in UuidInterface (and its implementations) suggests in phpdoc comment `\DateTime` as returned type.
I was wondering if it could make sense to change it to `\DateTimeInterface`, so when one day return type will be enforced, concrete implementations could be changed to `\DateTimeImmutable` instead (that's better)

**Comment by ramsey** [comment]
I agree. This would be a good change for version 4 of the library.

**Comment by garak** [comment]
I guess that we can close this issue, it looks like proposed changes have been made

**Comment by ramsey** [comment]
Thanks for keeping up with this. I need to get on top of things and make a big push for version 4 to get this and other things released.
