### ISSUE TITLE
for generate same hash ?

### ISSUE THREAD

**Issue by lcp0578** [ramsey/uuid#226]
```
$baseName = 'xxxx';
 // Generate a version 5 (name-based and hashed with SHA1) UUID object
$uuid = Uuid::uuid5(Uuid::NAMESPACE_DNS, $baseName);
for ($i = 0; $i < 10; $i++) {
       $result = $uuid->toString();
       var_dump($result);
}
```
generate same uuid?
why?

when i change  `$baseName = microtime(true) . mt_rand(0, 9);`

a rand base name, it not the same uuid?

but i can't confirm it no uuid confilct?

**Comment by jobe1986** [comment]
A version 5 UUID is garunteed to be the same ONLY when BOTH the namespace AND base name are the same in both attempts.

For example if you generate a version 5 NAMESPACE_DNS UUID for the base name "github.com" and then repeat the exercise, then you will get the same UUID both times.

If however either the namespace or the base name are different, then you will get a different UUID.

**Comment by ramsey** [comment]
I've got an email where it looks like @jobe1986 commented on this with a good answer to @lcp0578's question, but that comment is no longer here. @jobe1986, did you delete the comment? I came to thumbs-up it. :smile:

**Comment by jobe1986** [comment]
Yeah lil south doubt about the answer, doubted id read the original post right. Realised I had after deleting, by which point it was too late.

**Comment by jobe1986** [comment]
So to re-post what I had actually said previously:

With version 5 UUIDs you are guaranteed to get the same UUID every time you attempt to generate a UUID where the namespace and base name are the same.

For example if you generate 2 version 5 UUIDs with the DNS namespace and the name "github.com" you will get the same UUID both times. This is the intended behaviour for both version 3 and version 5 UUIDs.

**Comment by lcp0578** [comment]
@ramsey @jobe1986 thx, I got it.
