### ISSUE TITLE
Try/Catch on Uuid::uuid4()->fromString('foo'); does not catch error

### ISSUE THREAD

**Issue by Yamakasi** [ramsey/uuid#227]
I try to catch an error when validating a UUID, but when I first try to create a valid UUID from string upfront it does not catch the error:

```
                try {
                    $validUuidFromString = Uuid::uuid4()->fromString('foo');
                    $UuidType = Uuid::UUID_TYPE_RANDOM;
                }
                catch (UnsatisfiedDependencyException $e) {
                    echo 'Caught exception: ', $e->getMessage(), "\n";
                }
```

Should this not catch an error on the fromString() conversion already ? After it I check the version in some more code but I thought this should work.

**Comment by Yamakasi** [comment]
Is this a "bug" or a feature we need ?

**Comment by ramsey** [comment]
Are you seeing any errors at all? You should be seeing an `InvalidUuidStringException` instead of an `UnsatisfiedDependencyException`. You’re not catching it because the exception you’re attempting to catch is too specific.

**Comment by Yamakasi** [comment]
I'm not seeing any errors at all.

What you could add (which I do upfront now myself) try to create a dashed UUID out of 'foo' and if that matches (which I check after the creation with the ZendFramework UUID validator) it's a valid UUID format to start with.

Is that an idea ?

**Comment by Yamakasi** [comment]
Does this needs to become a feature request or can it be closed ?

**Comment by ramsey** [comment]
Sorry for the delay in responding. Can you provide more information on what it is you are asking? Are you making a feature request or reporting a bug?

**Comment by Yamakasi** [comment]
Hi, No problem, we are all busy! It would be nice if we can catch such specific behaviors. I need to check as I thought I fixed it back the days with checked the UUID format (as you described in another issue report).

**Comment by ramsey** [comment]
Is this still an issue?

I did finally notice an issue with the code example above:

``` php
$validUuidFromString = Uuid::uuid4()->fromString('foo');
```

This shouldn't be a legal statement, since `fromString()` is a static method, but PHP let's you do this anyway.

If you want to create a UUID from an existing string, you should do this:

``` php
use Ramsey\Uuid\Exception\InvalidUuidStringException;
use Ramsey\Uuid\Uuid;

try {
    $validUuidFromString = Uuid::fromString('foo');
} catch (InvalidUuidStringException $e) {
    echo 'Caught exception: ', $e->getMessage(), "\n";
}
```

Does this help?
