### ISSUE TITLE
How ramsey/uuid be unique world wide

### ISSUE THREAD

**Issue by saifuldhaka** [ramsey/uuid#230]
hi i used ramsey/uuid in my laravel project. i want to get a unique id for non registered member to track their activities. but uuid1() and uuid4() generates random id for same member with same pc. on the other side  uuid3() and uuid5() generate same id of my different testing pc. have any idea can make the unique identifier machine  based for each end user. thanks

**Comment by ramsey** [comment]
There are four types of UUIDs supported by ramsey/uuid:

* Version 1 is not random. It is based on time. However, it should be unique world-wide, but each time you generate it, you're going to get a new value.
* Versions 3 and 5 are not random, nor do they generate unique values. They are based on a namespace and will give you the same UUID each time for the same namespace and value. Version 3 uses MD5 to create a hash and version 5 uses SHA1.
* Version 4 is random and unique world-wide. Each time you generate one, you get a new random and unique value.

It sounds like you want each user to have the same UUID generated for them, based on their machine? I'm not sure exactly how you'd do this with full certainty, but you could generate a UUID, store that value in your database, and then set the UUID as a cookie in the user's browser. This is pretty much the same as using session cookies.

You could also generate a random UUID and call it your namespace, and then use the user's IP address to generate a version 5 UUID for them. If they visit from the same IP address each time, then you know it's the same user (unfortunately, offices and homes share the same IP address across multiple users, so this isn't exactly ideal).

It would look something like this:

``` php
define('MY_APP_NAMESPACE', '17ed68de-cf8f-450f-b28c-aa533fddaeee');
$userUuid = \Ramsey\Uuid\Uuid::uuid5(MY_APP_NAMESPACE, $_SERVER['REMOTE_ADDR']);
```

Does this help?

**Comment by jobe1986** [comment]
With regard to the choice of UUID for namespace, the common choice is often a version 1 UUID where the UUID library was able to correctly determine the systems ethernet address. An alternative to that and the method I personally prefer is to use a version 5 UUID with the DNS namespace and a DNS host name under a domain name I own, that represents the custom namespace.

**Comment by saifuldhaka** [comment]
you can check here http://dev.shopavision.com/uid
and is my test data 
ramsey uuid1: 3ac490ba-8181-11e8-97f5-002590e0bbe0
ramsey uuid3: 45a113ac-c7f2-30b0-90a5-a399ab912716
ramsey uuid4: 3933b0f7-cebc-4709-9416-c34c4ef8871b
ramsey uuid5: 26f68e65-670a-5cbb-bb36-77eb2297aa2f

every reload uuid1 and uuid4 returns same, 

@ramsey actually i want an id like, when i visit my site first time it will generate an id for me and this id will be always same for me when i back next time again. like a registered member.  it will be fixed unique for me, different id for other. it be always same until i not use different pc. 

``
define('MY_APP_NAMESPACE', '17ed68de-cf8f-450f-b28c-aa533fddaeee');
            
            // Generate a version 1 (time-based) UUID object
            $uuid1 = Uuid::uuid1();
            echo 'ramsey uuid1: '.$uuid1->toString() . "<br />"; // i.e. e4eaaaf2-d142-11e1-b3e4-080027620cdd
        
            // Generate a version 3 (name-based and hashed with MD5) UUID object
            $uuid3 = Uuid::uuid3(MY_APP_NAMESPACE, $_SERVER['REMOTE_ADDR']);
            echo 'ramsey uuid3: '.$uuid3->toString() . "<br />"; // i.e. 11a38b9a-b3da-360f-9353-a5a725514269
        ```

            // Generate a version 4 (random) UUID object
            $uuid4 = Uuid::uuid4();
            echo 'ramsey uuid4: '.$uuid4->toString() . "<br />"; // i.e. 25769c6c-d34d-4bfe-ba98-e0ee856f3e7a
        
            // Generate a version 5 (name-based and hashed with SHA1) UUID object
            $uuid5 = Uuid::uuid5(MY_APP_NAMESPACE, $_SERVER['REMOTE_ADDR']);
            echo 'ramsey uuid5: '.$uuid5->toString() . "<br />"; // i.e. c4a760a8-dbcf-5254-a0d9-6a4474bd1b62
`

**Comment by ramsey** [comment]
> actually i want an id like, when i visit my site first time it will generate an id for me and this id will be always same for me when i back next time again. like a registered member. it will be fixed unique for me, different id for other.

You should probably use a cookie for functionality like this.

**Comment by cafferata** [comment]
Maybe you're looking in the wrong direction? If you would ask me, I would advise you to look at an Javascript package that generates an unique browser fingerprint based on different browser properties. I hope this bring you some step further in your goals/needs. 

- https://browserleaks.com
- https://github.com/Valve/fingerprintjs2/blob/master/README.md
