### ISSUE TITLE
Documenting exception throws

### ISSUE THREAD

**Issue by marcosh** [ramsey/uuid#231]
It could be useful, especially when using IDEs, if the docblocks of the methods could describe also which exceptions are thrown.

Could it be a useful idea to annotate methods with the necessary `@throws` tags?

**Comment by ramsey** [comment]
This is a good idea. Are you interested in opening a pull request for this? If not, I can try to implement it soon. Thanks!

**Comment by marcosh** [comment]
I will try to do this in the next few days

**Comment by ramsey** [comment]
Implemented in #232
