### ISSUE TITLE
toString -> __toString

### ISSUE THREAD

**Issue by kelvindc** [ramsey/uuid#238]
in newest source toString() has changed to __toString(), breaks changes in previous version. Is it intended to be this way?

**Comment by ramsey** [comment]
The master branch is intended for the as-of-yet-unreleased 4.x series, and there will be some breaking changes in 4.0.0. Prior to any breaks, I will release 3.x versions that mark deprecations for anything that's intended to break in 4.0.0.

Let me know if you have any other questions or concerns about this. I promise not to break anything major without letting everyone know, and I promise to adhere to [semver](https://semver.org/). :smile:

**Comment by rainbow-alex** [comment]
Can you add __toString in the 3.x series (without removing toString)?

**Comment by ramsey** [comment]
No worries. I don’t want to break the interface for folks integrating with the 3.x series, but it’ll be on the interface for the 4.x series. Thanks!
