### ISSUE TITLE
php_uname() has been disabled for security reasons

### ISSUE THREAD

**Issue by s3lcsum** [ramsey/uuid#240]
`Ramsey\Uuid\Provider\Node\SystemNodeProvider::class` uses `php_uname()` method but secure configuration of _php.ini_ do not allows calling this command.

**Comment by ramsey** [comment]
### Project notes:

We had to check for a similar issue with `passthru()`. See #114 and 8d621488c4ec9c67444bc30534bc174b6bba07ee.

**Comment by bkayranci** [comment]
Bug Fixes #271 

PHP_OS predefined constant was used instead of php_uname() function.
