### ISSUE TITLE
Remove generic Exception

### ISSUE THREAD

**Issue by SendiMyrkr** [ramsey/uuid#254]
Hi, what do you think about replacing all generic \Exceptions by some more specific ones? Using of generic \Exception is really bad by my opinion. For example is not possible to set ignoring them in IDE(ie: PHPStorm in PHP Analysis) or static analysis when you want to distinguish code and domain errors.

**Comment by ramsey** [comment]
I'm all for this. It's something I've been meaning to do. Are you interested in working on this?

**Comment by SendiMyrkr** [comment]
I definitively may try to look at it and you'll see if is worth of something. :)

Now when i look closely on code i see generic exception only in phpDoc. I guess that reason, why they are there, is primarily for their using in optional libraries. How i said, i'll look at it closer, but do you have some quick clues if I missing something?

**Comment by ramsey** [comment]
I just looked through the source to see where generic \Exceptions are being thrown, and I can't find any. Can you point to some specific places in the source where you're seeing generic exceptions and want to replace them with specific ones?

**Comment by SendiMyrkr** [comment]
I have same findings, but they are in phpDocs. I guess that remove them from there or replacing by more explicit versions should be enough. Or what reason is for their using in phpDocs?

**Comment by ramsey** [comment]
It looks like they are in the PHP docblocks for interfaces, and maybe they're there because of the way tools like PhpStorm and phpstan handle static analysis of classes based on interfaces. I don't recall. :smile:

**Comment by SendiMyrkr** [comment]
I should understand it if should be there any implementation generated generic \Exception. But i don't see any. I belive is safe to remove them. I'll try it and will see what PHPStorm will say.

**Comment by felds** [comment]
The generic `\Exception` could be thrown by `random_bytes`, used by `RandomBytesGenerator`.

That's the only occurrence I could find of it.

Maybe it's worthy to catch it and then throw it as a more descriptive one?

**Comment by Majkl578** [comment]
https://github.com/ramsey/uuid/blob/430f1400eb66de54ace8c80d8b3d993ed2ee2fb7/src/UuidFactoryInterface.php#L42
https://github.com/ramsey/uuid/blob/430f1400eb66de54ace8c80d8b3d993ed2ee2fb7/src/UuidFactoryInterface.php#L63
https://github.com/ramsey/uuid/blob/430f1400eb66de54ace8c80d8b3d993ed2ee2fb7/src/UuidFactoryInterface.php#L41
https://github.com/ramsey/uuid/blob/430f1400eb66de54ace8c80d8b3d993ed2ee2fb7/src/UuidFactoryInterface.php#L84
https://github.com/ramsey/uuid/blob/430f1400eb66de54ace8c80d8b3d993ed2ee2fb7/src/UuidFactoryInterface.php#L84

**Comment by MrSpoocy** [comment]
What about 
https://github.com/ramsey/uuid/blob/f30bc1af81b1fdf5dec5ae085eb3ac2c59c32fe7/src/Uuid.php#L711

?

**Comment by ramsey** [comment]
I think these annotations are in the code because static analyzers complain when they aren’t there.

**Comment by felds** [comment]
@ramsey That's my reading as well. Many places in the code have the annotation, but only one place can actually throw an Exception.

`RandomBytesGenerator` bubbled the `* @Throws` annotation up to the interface, making every class that implements that interface to inherit the exception.

**Comment by MrSpoocy** [comment]
Here on point of view. I think a generation of uuidV4 NEVER throw a Exception. On v3 with parameter it is ok to throw a InvalidArgumentException.  About the function random_bytes try multiple fallback to work and at the end it call a Error and not a Exception. When we look to a normal database with auto_increment and we run on the limit of the max int value, the database must return a error and also the php script. What you want to do if you catch the error? The auto_increment value is full and there is no chance to handle the problem at this time.

my opinion ;)

**Comment by spectrox** [comment]
> If an appropriate source of randomness cannot be found, an Exception will be thrown.
https://secure.php.net/manual/en/function.random-bytes.php

I agree with @felds and think it would be perfectly fine to catch \Exception and check if the message is equal to "Could not gather sufficient random data" and throw our own exception in this case.

https://github.com/php/php-src/blob/623911f993f39ebbe75abe2771fc89faf6b15b9b/ext/standard/random.c#L85

**Comment by ramsey** [comment]
I've updated the `4.x` branch to remove all generic exceptions and replace them with exceptions that are specific to this library. Thanks for the recommendation!
