### ISSUE TITLE
Base 64 representation

### ISSUE THREAD

**Issue by nreynis** [ramsey/uuid#258]
It's common practice to use base64 encoding when passing uuids through URLs.
Do you think you could provide a support for that?

**Comment by ramsey** [comment]
I think that’s out of scope for this library. I’m curious how you’d expect it to work, though.

**Comment by nreynis** [comment]
My first idea was that we should add a Base64Codec. But I haven't look that much into it, so maybe I'm heading the wrong way.

**Comment by ramsey** [comment]
Can you provide some example code for how you think it would work?

In my mind, this is what I'm envisioning, which is why I don't see a need for this library to provide support for it:

``` php
$uuid = Ramsey\Uuid\Uuid::uuid4();

$base64 = base64_encode($uuid);
$uuidFromBase64 = Ramsey\Uuid\Uuid::fromString(base64_decode($base64));

echo $uuid . PHP_EOL;
echo $base64 . PHP_EOL;
echo $uuidFromBase64;
```

But it's possible you're thinking of it in a different way, and that's what I'd like to understand. :-)

**Comment by ramsey** [comment]
Alternately, here's how you'd do the same thing using bytes, which results in a shorter base64-encoded string:

``` php
$uuid = Ramsey\Uuid\Uuid::uuid4();

$base64 = base64_encode($uuid->getBytes());
$uuidFromBase64 = Ramsey\Uuid\Uuid::fromBytes(base64_decode($base64));

echo $uuid . PHP_EOL;
echo $base64 . PHP_EOL;
echo $uuidFromBase64;
```

**Comment by nreynis** [comment]
That's basicaly that, except in the case of UUID you will always have 2 '=' padding.
Thoses are not required for decoding and will trigger unnecessary percent encoding, which would defeat the purpose of having 'nicer' URLS.
You can safely trim them.
Also to make it URL safe you will also have to substitute '+' and '/', which will make it a 'base64url' encoding, not a basic base64 encoding.

https://en.wikipedia.org/wiki/Base64#URL_applications

```php
<?php
$uuidString = '23efce6292e439968b0a167566e0c8e8';

$base64Encoded = base64_encode(hex2bin($uuidString));
var_dump($base64Encoded); // I+/OYpLkOZaLChZ1ZuDI6A==
$base64UrlSafeEncoded = str_replace(['+', '/'], ['-','_'], substr($base64Encoded, 0, -2));
var_dump($base64UrlSafeEncoded); // I-_OYpLkOZaLChZ1ZuDI6A

var_dump(bin2hex(base64_decode(str_replace(['-','_'], ['+', '/'], $base64UrlSafeEncoded)))); // 23efce6292e439968b0a167566e0c8e8
```

**Comment by ramsey** [comment]
I would welcome another package that does this conversion for you, but I don't think it should be a concern of this package, which focuses only on UUIDs/GUIDs.
