### ISSUE TITLE
Enforce types

### ISSUE THREAD

**Issue by garak** [ramsey/uuid#264]
Since version 4 will be a major, BC break is allowed.
What about changing interfaces (and, of course, implemented classes) to enforce types?
I mean adding real type hints and return types, that now are only suggested via phpdoc comments.

**Comment by MarcusSchwarz** [comment]
Better yesterday than today!
![](https://media1.tenor.com/images/929ef78989437c2df790c0a16e966c18/tenor.gif?itemid=7244157)

**Comment by ramsey** [comment]
Merged into `4.x` in https://github.com/ramsey/uuid/commit/3c6b7fe96e1605d161c82fa49c2d949d67534af5. Thanks!
