### ISSUE TITLE
Can I limit uuid length?

### ISSUE THREAD

**Issue by mgkyawzayya** [ramsey/uuid#267]
example :

$uuid1 = Uuid::uuid1();
echo $uuid1->toString() . "\n"; // i.e. e4eaaaf2-d142-11e1-b3e4-080027620cdd

$uuid1 = Uuid::uuid1(7); // for length 7

**Comment by jobe1986** [comment]
Do you mean the length of the string returned by toString()?

**Comment by ramsey** [comment]
UUIDs cannot be shortened. They are 128-bit unsigned integers that are represented in a defined hexadecimal format. If you’re looking for shorter, non-sequential IDs, check out the hashids/hashids package or pascaldevink/shortuuid.

**Comment by mgkyawzayya** [comment]
Thanks a lot <3
