### ISSUE TITLE
Random generators doesn't correspond RFC4122

### ISSUE THREAD

**Issue by dkop** [ramsey/uuid#280]
According to [RFC4122](https://tools.ietf.org/html/rfc4122#page-14) 6 bits of random UUID should have fixed values. These bits has predefined values to detect UUID is random (in other words to check UUID is v4) nor Time-Based or Name-Based. But all random generators (RandomBytes, OpenSSL, MtRand) doesn't set these bits to values described by RFC.
Check this comment https://www.php.net/manual/en/function.uniqid.php#94959 for details how to generate random V4 UUID.

**Comment by ramsey** [comment]
Can you show an example where the version and variant bits aren’t being set in random UUIDs? Thanks!

**Comment by ramsey** [comment]
I think I see the confusion. 😀

The random generators are there only to generate the bytes, not to arrange them according to RFC 4122. When the factory gets the bytes from the generator, in then applies the variant and version bits here: https://github.com/ramsey/uuid/blob/35cf50d7b408fdfc2bc78508a0dafe1778b90354/src/UuidFactory.php#L243

Hope this helps. Let me know if you’re seeing any problems generating the UUIDs. You should be able to see the variant and version in the string version of the UUID. See the slides here for details: https://speakerdeck.com/ramsey/identify-all-the-things-with-uuids-true-north-php-2016?slide=13

Thanks for reporting, though! Happy holidays!
