### ISSUE TITLE
Moontoast Math is abandoned

### ISSUE THREAD

**Issue by alphametric** [ramsey/uuid#288]
After performing a `composer update` this morning, I received this message in the terminal:

`Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead`

I'm not certain if `brick/math` is a drop-in replacement, but thought you should know.

**Comment by ramsey** [comment]
Thanks! I know. I'm also the author of moontoast/math. 😁

**Comment by alphametric** [comment]
Ah okay cool. So is brick/math a drop in replacement?

**Comment by ramsey** [comment]
Not exactly. I'm getting close to releasing an alpha version of ramsey/uuid 4.0.0 will will eliminate the need for moontoast/math. For now, continuing to use moontoast/math with the 3.x series is the correct approach.

**Comment by ramsey** [comment]
Reopening so I can pin this issue to help others with similar concerns.

**Comment by alphametric** [comment]
Got it. Thanks, I’ll keep an eye on it :)

**Comment by tillkruss** [comment]
I've had to use `composer require moontoast/math "1.1.2 as 1.99.0"` to be able to install my Laravel application on Heroku.

**Comment by ramsey** [comment]
What errors were you getting? While I’ve marked the package as “abandoned,” this shouldn’t keep you from being able to install it.

**Comment by tillkruss** [comment]
```
Your requirements could not be resolved to an installable set of packages.

Problem 1
- don't install phpseclib/bcmath_compat 1.0.3|don't install php 7.3.13
- composer.json/composer.lock requires php 7.3.* -> satisfiable by php[7.3.13].
- Installation request for phpseclib/bcmath_compat 1.0.3 -> satisfiable by phpseclib/bcmath_compat[1.0.3].
```

See https://github.com/phpseclib/bcmath_compat/issues/1

**Comment by ramsey** [comment]
Thanks for pointing that out!

FWIW, that has nothing to do with abandoning the package. I think there’s a bcmath conflict, but I’m not sure right now. We’ll use the issue on phpseclib/bcmath_compat to discuss it.

**Comment by jonnott** [comment]
I know it's tangental, but this lib also relies on moontoast/math, so any kind of drop-in replacement that could cover that would be great too..

https://github.com/pascaldevink/shortuuid/issues/68

Although, it's not been updated for looooong, so if ramsey/uuid could have an option for the 'short' aspect (turning a UUID into a URL-safe string, and back), that'd be a ++ all round!

**Comment by ramsey** [comment]
@jonnott Thanks for linking to that thread here.

I'm also linking to this thread, so I can try to start collecting all these in one place. 😄 

https://github.com/laravel/framework/issues/23291#issuecomment-573825311

**Comment by ramsey** [comment]
> For the 3.x series of ramsey/uuid, you may continue to use moontoast/math. **It's not going anywhere**—it just won't get anymore updates or features. Version 4.x of ramsey/uuid (alpha version coming soon 🤞) gets rid of the need for moontoast/math.

**Comment by LorenzoSapora** [comment]
On v4.0.0-alpha the composer still has moontoast/math as a requirement. Is this an oversight, or are you still relying on that package until 4.0.0 proper?

**Comment by ramsey** [comment]
It’s required in `require-dev` to ensure certain tests continue to pass, but it’s not required by the library.

**Comment by anususmi** [comment]
After "composer update" "php artisan" command gives,

Class 'Moontoast\Math\AbstractBigNumber' not found
     My php version 7.3.15
     I try installing  " composer require moontoast/math", "composer require brick/math", "sudo apt install php7.3-bcmath".

But still getting the above error, any idea what goes wrong.
Thanks in advance ...

**Comment by ramsey** [comment]
@anususmi, it sounds like you might be using Laravel. What version of Laravel are you using?

Is there more to the error message, like a stacktrace? If so, please post the full stacktrace.

Also, please enter `composer show` and paste the full output here. That will help.

Thanks!

**Comment by anususmi** [comment]
Thanks for quick reply,
1. Laravel version - 5.7
2. Error Message,
        PHP Fatal error:  Uncaught Error: Class 'Moontoast\Math\AbstractBigNumber' not found in /home/username/www/project/vendor/moontoast/math/src/Moontoast/Math/BigNumber.php:28
Stack trace:
#0 /home/username/www/project/vendor/composer/ClassLoader.php(444): include()
#1 /home/username/www/project/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/username/...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Moontoast\\Math\\...')
#3 [internal function]: spl_autoload_call('Moontoast\\Math\\...')
#4 /home/username/www/project/vendor/ramsey/uuid/src/FeatureSet.php(323): class_exists('Moontoast\\Math\\...')
#5 /home/username/www/project/vendor/ramsey/uuid/src/FeatureSet.php(244): Ramsey\Uuid\FeatureSet->hasBigNumber()
#6 /home/username/www/project/vendor/ramsey/uuid/src/FeatureSet.php(124): Ramsey\Uuid\FeatureSet->buildNumberConverter()
#7 /home/username/www/project/vendor/ramsey/uuid/src/UuidFactory.php(64): Ramsey\Uuid\FeatureSet->__construct()
#8 /home/su in /home/username/www/project/vendor/moontoast/math/src/Moontoast/Math/BigNumber.php on line 28

3. Composer 
      
![image](https://user-images.githubusercontent.com/33715949/75603075-ff4b5780-5af0-11ea-92b7-caf6d8893e57.png)

**Comment by ramsey** [comment]
@anususmi, this doesn't make any sense. 😄 

It's loading `BigNumber`, but then it fails because it can't find `AbstractBigNumber`. At least, that's how I read this stacktrace. It sounds like maybe your autoloader is corrupted in some way.

I recommend deleting your `vendor/` directory entirely. Then, run `composer install` again and see if you run into the same problem. If you do, you might also try deleting your `composer.lock` file, along with the `vendor/` directory and re-running `composer install`.

The error you're getting should not be possible if the autoloader is working correctly.

**Comment by ramsey** [comment]
If you still have issues after that, please paste your full `require` and `require-dev` sessions from `composer.json` here, so I can try to reproduce this. Thanks!

**Comment by vbasky** [comment]
<img width="928" alt="Screen Shot 2020-03-01 at 12 34 57 pm" src="https://user-images.githubusercontent.com/287302/75617879-21101180-5bb9-11ea-8472-75f1251d7f2f.png">

Even after deleting my `vendor` directory I still get this error

**Comment by ramsey** [comment]
@vbasky, the “abandoned” message is expected. See the explanation earlier in this thread.

My comment about deleting the vendor directory was meant to be for @anususmi, who is getting this error:

    PHP Fatal error: Uncaught Error: Class 'Moontoast\Math\AbstractBigNumber' not found

**Comment by jonnott** [comment]
@ramsey as ramsey/uuid 4.0 is out, can this all be resolved now?

**Comment by ramsey** [comment]
@jonnott I might leave it open for a while longer as "informational," since so many were complaining that it's an *error* they're getting (for folks still using version 3). 😁

**Comment by jonnott** [comment]
Thanks @ramsey. I'm assuming once packages like shortuuid are able to use uuid v4, the abandoned warning wouldn't be shown anymore by Composer .. ?

**Comment by ramsey** [comment]
This is correct. However, the warning won't hinder your use of either library. It's a nice, colorful message you get to see when you run `composer install`. 😉

**Comment by Oluwatobilobaoke** [comment]
> Not exactly. I'm getting close to releasing an alpha version of ramsey/uuid 4.0.0, which will eliminate the need for moontoast/math. For now, continuing to use moontoast/math with the 3.x series is the correct approach.

So for now we should ignore this error and continue with our projects or run composer require "moontoast/math"???

**Comment by Oluwatobilobaoke** [comment]
@ramsey  just did composer install on a project and I'm getting this error:
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Generating optimized autoload files
Deprecation Notice:
I'm on version 4.0 how do I go about it

**Comment by Oluwatobilobaoke** [comment]
> This is correct. However, the warning won't hinder your use of either library. It's a nice, colorful message you get to see when you run `composer install`. 😉

I'm still receiving the it

**Comment by ramsey** [comment]
Try the command `composer depends moontoast/math` to see if any other packages depend on it.

**Comment by Oluwatobilobaoke** [comment]
> Try the command `composer depends moontoast/math` to see if any other packages depend on it.

λ composer depends moontoast/math
after running this I got this seems laravel/telescope depends on it
laravel/telescope  v3.3.0  requires  moontoast/math (^1.1)

**Comment by ramsey** [comment]
Thanks for checking on that. laravel/telescope uses moontoast/math, so they'll have to make changes in order for you to stop receiving this message.

**Comment by Oluwatobilobaoke** [comment]
@ramsey  Thank you, let me go and open a ticket then at laravel/telescope

**Comment by BenMorel** [comment]
I actually [tried to remove](https://github.com/laravel/telescope/pull/896) their dependency on `moontoast/math`, but it's actually used by `ramsey/uuid` (`< 4.0`):

> Ramsey\Uuid\Exception\UnsatisfiedDependencyException: Cannot call Ramsey\Uuid\Converter\Number\DegradedNumberConverter::toHex without support for large integers, since integer is an unsigned 128-bit integer; Moontoast\Math\BigNumber is required. 

So the best thing to do is to request them to switch to `ramsey/uuid`: `^4.0`.

**Comment by Oluwatobilobaoke** [comment]
Yes according to a recently raised [issue ](https://github.com/laravel/telescope/issues/815)they said they will fix it in Telescope V4 which is yet to be released

**Comment by alecpl** [comment]
What about the tests? I see `BigNumber::convertToBase10($var, 16)` is the only thing in use from `moontoast/math`. Can't this be replaced with something from `brick/math`? If there isn't, looking at the implementation, it should be possible to just copy this static method code here and require php-bcmath.

**Comment by ramsey** [comment]
moontoast/math is in the require-dev dependencies, so it shouldn't affect your use of the library.

**Comment by anususmi** [comment]
@ramsey Thanks :-), issue solved after deleting my vendor and composer install
