### ISSUE TITLE
Adopt Symfony's Strict UUID validation

### ISSUE THREAD

**Issue by agustingomes** [ramsey/uuid#291]
As it's currently the case, none of the validators built in the library and used in the `Uuid::isValid()` method, are checking if a given UUID string adheres to any specific UUID version. This could cause potential issues when we rely on this method to validate user defined UUID's.

One scenario I came across was when i changed a couple of random characters on a UUID string, the application let it through as a valid UUID, but this caused some problems later on when API clients were receiving this particular UUID.

One of the ideas I have in mind, is to require `symfony/validation` package, and leverage on the strict validation to ensure that when we call `Uuid::isValid()` it returns false on strings that don't adhere to any UUID version. Another idea would be to add a call to `isValid` from the `fromString` method, to perform this validation implicitly. 

An alternative to this addition, is to keep using the `symfony/validation` package separately, but this is a bit inconvenient since it's hard to enforce automatically the validation of user provided UUID's, and all developers would have to keep in mind to explicitly use it.

For context, during an API endpoint development, we needed to provide the ability to clients to provide specific UUID's. during one test, I did a manual change of the first 5 characters of an UUID string, having ended with this string: `abed5a25-cf8d-6345-a15f-8afb78cc7df0`. 

The operation to create an entity with that UUID succeeded, but it caused problems in our Javascript clients and some PHP services using explicitly the Symfony's UUID validator.

P.S: I see there's some suggestions of similar issues, but i would like to know your opinion about this particular use case I came across.

**Comment by ramsey** [comment]
Take a look at version 4.0.0-alpha1. In the 4.x series, you can do this:

``` php
$factory = new UuidFactory();
$factory->setValidator(new MyValidator());

Uuid::setFactory($factory);

if (Uuid::isValid($uuid)) {
    // validates the UUID according to your custom validator
}
```

Does this accomplish what you're looking to do?

The default validator continues to validate UUIDs loosely, as it does in 3.x. However, note the difference in the type of object returned (using the string you provided above):

``` php
$uuid = Uuid::fromString('abed5a25-cf8d-6345-a15f-8afb78cc7df0');
var_dump(get_class($uuid));
```

This dumps `string(28) "Ramsey\Uuid\Nonstandard\Uuid"`.

As you can see, it's returning a `Ramsey\Uuid\Nonstandard\Uuid`. If it were a valid RFC 4122 UUID, it would return an instance of `Ramsey\Uuid\Rfc4122\UuidInterface` of the specific UUID version. For example:

``` php
$uuid = Uuid::fromString('15f880c6-97db-4245-9010-6f973c321259');
var_dump(get_class($uuid));
// string(26) "Ramsey\Uuid\Rfc4122\UuidV4"
```

If you want to make the library more restrictive, you may do this:

``` php
$factory = new UuidFactory();
$factory->setValidator(new Rfc4122\Validator());

Uuid::setFactory($factory);

$uuid = Uuid::fromString('abed5a25-cf8d-6345-a15f-8afb78cc7df0');
```

This ensures the string must match the expected format for an RFC 4122 UUID. If it doesn't, it will throw the exception `Ramsey\Uuid\Exception\InvalidUuidStringException`.

**Comment by agustingomes** [comment]
Hi @ramsey 

First of all, thank you for your time and looking into the issue.

```php
$factory = new UuidFactory();
$factory->setValidator(new Rfc4122\Validator());

Uuid::setFactory($factory);

$uuid = Uuid::fromString('abed5a25-cf8d-6345-a15f-8afb78cc7df0');
```

This suggestion you provided will work well for when we adopt the new version. I will close the ticket.
