### ISSUE TITLE
Psalm annotations in brick/math

### ISSUE THREAD

**Issue by BenMorel** [ramsey/uuid#294]
Hi 👋 `brick/math` author here.

Just to let you know, version [0.8.12](https://github.com/brick/math/releases/tag/0.8.12) brings Psalm annotations `@psalm-immutable` and `@psalm-pure` to BigNumber classes,  you should now be able to get rid of `@psalm-suppress ImpureMethodCall` in BrickMathCalculator!

**Comment by ramsey** [comment]
Thanks, @BenMorel!
