### ISSUE TITLE
Trait 'Ramsey\Uuid\DeprecatedUuidMethodsTrait' not found 

### ISSUE THREAD

**Issue by h-o-sein** [ramsey/uuid#305]
## Describe the bug

Symfony\Component\ErrorHandler\Error\FatalError
Trait 'Ramsey\Uuid\DeprecatedUuidMethodsTrait' not found 

## Environment details

 - OS: CentOS 7
 - ramsey/uuid version: 4.0.1
 - Laravel version: 7.3.0
 - Laravel locale: en
 - Laravel config cached: false
 - PHP version: 7.3.16

**Comment by ramsey** [comment]
What were you attempting to do when you got this error? Can you share some code?

**Comment by h-o-sein** [comment]
![Screen Shot 2020-04-01 at 8 21 11 PM](https://user-images.githubusercontent.com/9271127/78158397-6cd30680-7456-11ea-8806-13d1701302dc.png)

**Comment by ramsey** [comment]
This is a screenshot of code from ramsey/uuid. Can you share code that shows how you are using ramsey/uuid in your own application, please?

**Comment by ramsey** [comment]
Since you closed this, I assume you were able to resolve it? Would you mind leaving a comment to explain how you resolved it, in case others experience the same issue in the future? Thanks!

**Comment by h-o-sein** [comment]
> Since you closed this, I assume you were able to resolve it? Would you mind leaving a comment to explain how you resolved it, in case others experience the same issue in the future? Thanks!

Hi
Once I completely deleted Laravel and reinstalled it, it was fixed.😊
