### ISSUE TITLE
Uuid::fromHex($hex)

### ISSUE THREAD

**Issue by pluk77** [ramsey/uuid#308]
Would it be possible to add a Uuid::fromHex($hex) function that would basically do the same as this:

    $hex = new Hexadecimal('0x1EA78DEB37CE625E8F1A025041000001');
    $uuid = Uuid::fromBytes((string) hex2bin($hex));

The function could either take a hexadecimal string, or even a Hexadecimal object.

Something like this:

    $hex = new Hexadecimal('0x1EA78DEB37CE625E8F1A025041000001');
    $uuid = Uuid::fromHex($hex);

or:

    $uuid = Uuid::fromHex('0x1EA78DEB37CE625E8F1A025041000001');

**Comment by ramsey** [comment]
I like this idea, and I'd be willing to add this function (or accept a PR that does). 😄

**Comment by pluk77** [comment]
I have created a PR

**Comment by ramsey** [comment]
Thanks!
