### ISSUE TITLE
Remove phpstan/phpdoc-parser from require-dev

### ISSUE THREAD

**Issue by ondrejmirtes** [ramsey/uuid#313]
Hi,
I'd like to know if you have a specific reason to require `phpstan/phpdoc-parser` in your composer.json? It shouldn't be necessary unless you're parsing PHPDocs in your library, which seems out of scope :) Thank you.

**Comment by ramsey** [comment]
I honestly don't know why I have phpstan/phpdoc-parser required. 😆

**Comment by ramsey** [comment]
I included it in this commit, but I don't recall why. https://github.com/ramsey/uuid/commit/0d7b8c2b7a99a5bf69e96b84ead75c74290a5fb2

**Comment by ondrejmirtes** [comment]
I stumbled upon this because I was inspecting the list of dependent packages on this one so that I can figure out how serious should I be about backwards compatibility. And this one caught my eye because I use it in my projects but I didn't see any reason why it would depend on the phpdoc-parser :)

It's not necessary for running PHPStan, so if you don't find any other reason, feel free to remove it :) Thanks.

**Comment by ramsey** [comment]
Reopening to remind me to remove this (or for anyone else to submit a PR to remove it).

**Comment by mitch292** [comment]
Hi - I submitted a PR :)
