### ISSUE TITLE
Make `serialize(UuidInterface)` more compact?

### ISSUE THREAD

**Issue by Ocramius** [ramsey/uuid#318]
Currently, `serialize(Ramsey\Uuid\Rfc4122\UuidV4)` generates a string of 75 chars:

```
$uuid = Uuid::fromString("945de397-0ddd-4b4e-ac79-42b01308ba43");
var_dump(serialize($uuid));
```

Output:

```
string(75) "C:26:"Ramsey\Uuid\Rfc4122\UuidV4":36:{9ff8edd6-33ba-4156-aaec-a0726ad5a78f}"
```

We can reduce this by a lot by using `Uuid#getBytes()` in `Uuid#serialize()`

This can then be combined with a `strlen()` check during `unserialize()` (for BC compliance) to decide whether to use `Uuid::fromBytes()` or `Uuid::fromString()` during de-serialization.

In a later release, the `strlen()` check may be dropped.

To be noted: binary strings are not necessarily nice to work with, but so are PHP serialized strings anyway. Some output may be scrambled:

```
var_dump(serialize(
    Uuid::fromString("945de397-0ddd-4b4e-ac79-42b01308ba43")
        ->getBytes()
));
```

Produces following hard-to-read representation:

```
�KN�yB��C";"s:16:"�]��
```

**Comment by sserbin** [comment]
fwiw that fix (https://github.com/ramsey/uuid/commit/22ee596348c02a5f2d6cc4ce4b7cc59264a54194 , released in 4.1.0) is somewhat a BC break in case you we using json serialization (as it's going to be broken now that id serializes to binary string)

**Comment by ramsey** [comment]
@sserbin It protects against the BC break by checking the string length. Have you encountered a BC problem with it?

**Comment by sserbin** [comment]
> It protects against the BC break by checking the string length

@ramsey right, I was referring more to serialize() part of the change: if you happened to json encode uuids - that won't longer work. There's an argument that there's a separate `jsonSerialize()` for that though, hence why "somewhat a bc break", guess not many folks would come across this. (might help to mention this in changelog though)

For more context on specific use case - doctrine entities (holding uuids) were `serialize()`d and then json encoded and sent to a queue

**Comment by ramsey** [comment]
I see what you're saying. So, in Doctrine's case, they're treating the format of the serialized value as part of the public interface of the library?

**Comment by sserbin** [comment]
Not quite, as doctrine itself wasn't doing serialization (entities are just popo's in the end) - framework did. Which you also can't probably blame since it's only issue is assumption that everything that `serialize()`s would be `json_encode()`able
