### ISSUE TITLE
Uuid::uuid4 returns an object instead of a string

### ISSUE THREAD

**Issue by arianitu** [ramsey/uuid#32]
Uuid::uuid4 seems to return an object instead of a string, this seems a bit weird because it fails validation checks (is_string)

The way I use it now is: (string) Uuid::uuid4(). 

Anyone else have similar issues?

**Comment by mervick** [comment]
Why It returns object? I spent 3 hours to understand where was error.
It's very strange behavior..

**Comment by ramsey** [comment]
The examples in the README show that it returns an object, and the [API documentation](https://docs.benramsey.com/ramsey-uuid/3.7.3/Ramsey/Uuid/Uuid.html#method_uuid4) shows that it returns an object. Do you have a recommendation for how I can communicate this better to avoid issues like this?

**Comment by mervick** [comment]
I have no idea how to make it better in documentation, especially when people like me don't read documentation for things like this...
From today I will use wrapper for this
```php
function uuid4() {
    return \Ramsey\Uuid\Uuid::uuid4()->toString();
}
```

**Comment by ramsey** [comment]
Creating a wrapper works. You could also cast the object to a string:

``` php
echo (string) \Ramsey\Uuid\Uuid::uuid4();
```

**Comment by mervick** [comment]
Yes, I understand that now, but my issue was something like below

```php
// my code
$model = new Model()
$model->name = 'Some Name';
$model->save();

// in model behavior, set default values
$model->uuid = \Ramsey\Uuid\Uuid::uuid4();
```

Somewhere in PDO class of Phalcon framework (compiled into PHP extension),  
it checks type of value
https://github.com/phalcon/cphalcon/blob/ec30392d477d7e7e1a4283e0f0f33ef80ecd25f6/phalcon/db/adapter/pdo.zep#L251-L285

And at the end it prepare very strange SQL query
```sql
INSERT INTO `table` (`uuid`, `xxx`, `xxx`, `xxx`, `xxx`, `xxx`, `xxx`) VALUES (7cb1b147-b4af-44e6-b419-1617c256fae9, ?, DEFAULT, ?, ?, ?, ?)
```
