### ISSUE TITLE
\Ramsey\Uuid\Uuid::uuid4() does not return an instance implementing Ramsey\Uuid\Rfc4122\UuidInterface as per the docs

### ISSUE THREAD

**Issue by PeeHaa** [ramsey/uuid#342]
The [getting started guide](https://uuid.ramsey.dev/en/latest/quickstart.html#using-ramsey-uuid) says the following:

When using `Ramsey\Uuid\Uuid::uuid4()` it:

> will return an instance of Ramsey\Uuid\Rfc4122\UuidV4.

However it does not.

```php
var_dump(\Ramsey\Uuid\Uuid::uuid4() instanceof \Ramsey\Uuid\Rfc4122\UuidV4); // false
```

This is on current latest: 4.1.1

**Comment by ramsey** [comment]
Please see the discussion on #327. This is a known issue that might be considered a documentation error, rather than a bug in the code. I'm still trying to decide what to do here.
