### ISSUE TITLE
Laravel Str::uuid() work, Str::orderedUuid() not work. Ramsey/Uuid/Exception/BuilderNotFoundException with message 'Could not find a suitable builder for the provided codec and fields'

### ISSUE THREAD

**Issue by affinage-digital** [ramsey/uuid#345]
## Describe the bug

On Ubuntu from homestead Str::orderedUuid() works great.
But on Windows Server 2016 we have error
```
Ramsey/Uuid/Exception/BuilderNotFoundException with message 'Could not find a suitable builder for the provided codec and fields'
```

## To Reproduce...

See first screenshot

## Expected behavior

Str::orderedUuid() would return "123e4567-e89b-12d3-a456-426614174000"

## Screenshots or output

![img-2020-10-14-20-11-10](https://user-images.githubusercontent.com/42941/96030350-84d20c80-0e21-11eb-856a-9a456fc024d6.png)

![img-2020-10-14-20-26-53](https://user-images.githubusercontent.com/42941/96030367-88659380-0e21-11eb-9c3d-f9f3903aa3cd.png)

## Environment details

 - OS: Windows Server 2016 (x64)
 - PHP version: 
PHP 7.3.13 (cli) (built: Dec 17 2019 13:16:21) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies

 - ramsey/uuid version: 4.1.1
 - php.ini: 
```
[WebPIChanges]
error_log = C:\Windows\temp\PHP73x64_errors.log
upload_tmp_dir = C:\Windows\temp
session.save_path = C:\Windows\temp
cgi.force_redirect = 0
cgi.fix_pathinfo = 1
fastcgi.impersonate = 1
fastcgi.logging = 0
max_execution_time = 300
date.timezone = Europe/Moscow
extension_dir = "C:\Program Files\PHP\v7.3\ext\"

short_open_tag = On
display_errors = On
max_input_time = 240
max_input_vars = 10000
mbstring.func_overload = 2
mbstring.internal_encoding = UTF-8
```

## Additional context

Searching for the problem on google didn't help. Look like nobody seems to have encountered this problem

**Comment by ramsey** [comment]
Were you able to solve this issue? I don't have a lot of experience with Laravel, Homestead, or Windows Server 2016, so this isn't something I've been able to investigate on my own.

**Comment by affinage-digital** [comment]
We haven't found a solution. We stopped using `Str::orderedUuid()`.
I close the issue.
