### ISSUE TITLE
Validation pattern not accepted by preg_match

### ISSUE THREAD

**Issue by DBX12** [ramsey/uuid#356]
## Describe the bug

The pattern provided by `GenericValidator::getPattern()` is not suitable for usage with `preg_match()`

## To Reproduce...

Reproducible by running this sample code. The `$testUuid` should be valid.
``` php
<?php
require_once 'vendor/autoload.php';
$validator = new Ramsey\Uuid\Validator\GenericValidator();
$testUuid = 'c2e2d482-011a-4adc-a115-5cfe60785bcc';
var_dump(preg_match($validator->getPattern(),$testUuid));
```
Received output:
```
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/dbx12/PhpstormProjects/voting/test.php on line 5
PHP Stack trace:
PHP   1. {main}() /tmp/test.php:0
PHP   2. preg_match() /tmp/test.php:5
bool(false)
```

## Expected behavior

- The pattern is accepted by `preg_match()`.
- The pattern validates UUIDs correctly

## Screenshots or output

n/a, all output is pasted above

## Environment details

 - OS: Linux, Kernel 5.4.0-56-generic / Linux Mint Mate 20
 - PHP version: 7.4.3
 - ramsey/uuid version: 4.1.1

**Comment by ramsey** [comment]
You will need to put delimiters around the pattern. It is designed this way so that you may use the pattern in other contexts, such as within other patterns.

```php
var_dump(preg_match('/' . $validator->getPattern() . '/',$testUuid));
```

**Comment by DBX12** [comment]
Oh man, it was obvious :man_facepalming: 
Sorry for bothering you and thanks for the heads up.
