### ISSUE TITLE
Declaration of Ramsey\Uuid\Lazy\LazyUuidFromString::equals(?Ramsey\Uuid\Lazy\object $other): incompatible with Ramsey\Uuid\UuidInterface::equals(?Ramsey\Uuid\object $other): bool

### ISSUE THREAD

**Issue by Zarganwar** [ramsey/uuid#358]
**Declaration of Ramsey\Uuid\Lazy\LazyUuidFromString::equals(?Ramsey\Uuid\Lazy\object $other): bool must be compatible with Ramsey\Uuid\UuidInterface::equals(?Ramsey\Uuid\object $other): bool**

## Environment details

 - OS: [e.g. Debian GNU/Linux 10 (buster) - Linux 4.9.0-4-amd64]
 - PHP version: [e.g. 7.1.33]
 - ramsey/uuid version: [e.g. 4.1.1]

**Comment by ramsey** [comment]
Version 4 of ramsey/uuid supports PHP versions 7.2., 7.3, 7.4, and 8.0. I'm unable to help with issues on PHP 7.1.
