### ISSUE TITLE
UUID::uuid4 generating a UUID containing a "y" character.

### ISSUE THREAD

**Issue by mogilvie** [ramsey/uuid#362]
## Describe the bug

UUID::uuid4 generates a UUID containing a 'y' in the first number set.

"dabf*y*08d-3aa6-11e9-b1fd-00163e76b1b2"

The number generates, and is accepted by Doctrine during persistence, but then fails when hydrating on loading.

Uncaught PHP Exception Doctrine\DBAL\Types\ConversionException: "Could not convert database value "dabfy08d-3aa6-11e9-b..." to Doctrine Type uuid"

## To Reproduce...

Can't reproduce, seems random.

## Expected behavior

Expect to generate a number that validates.

## Screenshots or output

![image](https://user-images.githubusercontent.com/7894754/108999743-a4642600-769a-11eb-9a8c-a06ee47b6ec6.png)

![image](https://user-images.githubusercontent.com/7894754/108999773-b34ad880-769a-11eb-8f3e-e0d07cf8ddbb.png)

## Environment details

 - LAMP
 - PHP version: 7.2
 - ramsey/uuid version: 4.1.1
 - ramsey/uuid-doctrine version: 1.6.0

## Additional context

    /**
     * @var string
     *
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    protected $id;

**Comment by mogilvie** [comment]
Sorry, disregard. This UUID was generated prior to using the Ramsey bundle.

**Comment by ramsey** [comment]
Thanks for letting me know!
