### ISSUE TITLE
The getLocalDomainName and getLocalIdentifier methods are not existed！

### ISSUE THREAD

**Issue by MsZhu** [ramsey/uuid#371]
<?php
        use Ramsey\Uuid\Uuid;

        $uuid = Uuid::uuid2(Uuid::DCE_DOMAIN_PERSON);
        
        printf(
            "UUID: %s\nVersion: %d\nDate: %s\nNode: %s\nDomain: %s\nID: %s\n",
            $uuid->toString(),
            $uuid->getFields()->getVersion(),
            $uuid->getDateTime()->format('r'),
            $uuid->getFields()->getNode()->toString(),
            $uuid->getLocalDomainName(),
            $uuid->getLocalIdentifier()->toString()
        );

**Comment by ramsey** [comment]
Thanks for reporting this. It looks like it's caused by this code:

https://github.com/ramsey/uuid/blob/90a87a75432831ec4882ddea9cf49ee9127130ef/src/UuidFactory.php#L487-L491

As a work-around, you may do this:

```php
use Ramsey\Uuid\FeatureSet;
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidFactory;

$uuidFactory = new UuidFactory(new FeatureSet());
$uuid = $uuidFactory->uuid2(Uuid::DCE_DOMAIN_PERSON);

printf(
    "UUID: %s\nVersion: %d\nDate: %s\nNode: %s\nDomain: %s\nID: %s\n",
    $uuid->toString(),
    $uuid->getFields()->getVersion(),
    $uuid->getDateTime()->format('r'),
    $uuid->getFields()->getNode()->toString(),
    $uuid->getLocalDomainName(),
    $uuid->getLocalIdentifier()->toString()
);
```
