### ISSUE TITLE
PHP 8.1 Compatibility Issue

### ISSUE THREAD

**Issue by zorro1199** [ramsey/uuid#378]
Uuid.php, \Builder\BuilderCollection.php, \Provider\Node\NodeProviderCollection.php and \Lazy\LazyUuidFromString.php make use of the broken `Serializable` interface and cause deprecation warnings with PHP 8.1. `__serialize()` should be used instead: [https://wiki.php.net/rfc/phase_out_serializable](https://wiki.php.net/rfc/phase_out_serializable)

**Comment by ramsey** [comment]
Thanks for reporting this!

**Comment by ramsey** [comment]
This is fixed in version 4.2.2.
