### ISSUE TITLE
Can i check the version of a Ramsey\Uuid\UuidInterface implemetation?

### ISSUE THREAD

**Issue by danfoley** [ramsey/uuid#389]
I'm getting a `Ramsey/Uuid/UuidInterface` type uuid passed into the constructor of my class. I want to validate that it's a version 6 uuid. However the `->getVersion()` method is deprecated in favor of the `->getFields()->getVersion()`. That is only available on RFC4122 types. 

So is there a way to get the version number of a `Ramsey/Uuid/UuidInterface` type uuid?

ex:
```` php
$uuid = Ramsey/Uuid/Uuid::uuid6();
$uuid->.....getVersion() = 6;
````

**Comment by smaddock** [comment]
I have the same question. After verifying a string `isValid()` and converting it to an object `fromString()`, using the documented ` instanceof \Ramsey\Uuid\Rfc4122\UuidV4` (or whatever version) returns false, but `->getFields()->getVersion()` returns the version number at least, although my IDE doesn't like it. I've read through #327 and #521 as well which are related but I don't see a definitive answer for checking which version a string is.
