### ISSUE TITLE
Does COMB have Year 2059 Problem?

### ISSUE THREAD

**Issue by mpyw** [ramsey/uuid#392]
UUIDs generated by `CombGenerator` (called as *Ordered UUID* in Laravel) contains a 48-bit timestamp, but its precise is on the order of 10 microseconds.

```
(2^48)/(86400*100000*365) + 1970 ≈ 2059
```

It means that in 2059, we will spend all reserved spaces for orderd UUIDs. Is it already recognized by contributors and users?

----

NOTE: ULID, which is a similar concept, claims that space will not be exhausted until the year 10889 because it is on the order of milliseconds.

- [ulid/spec: The canonical spec for ulid](https://github.com/ulid/spec)

**Comment by mpyw** [comment]
Currently I'm planning to use [robinvdvleuten/php-ulid](https://github.com/robinvdvleuten/php-ulid) through [mpyw/uuid-ulid-converter](https://github.com/mpyw/uuid-ulid-converter) to avoid this problem.

**Comment by mpyw** [comment]
Currently I'm planning to use @robinvdvleuten's [robinvdvleuten/php-ulid](https://github.com/robinvdvleuten/php-ulid) through [mpyw/uuid-ulid-converter](https://github.com/mpyw/uuid-ulid-converter) to avoid this problem.

**Comment by ramsey** [comment]
@mpyw, sounds good. I can't change UUIDs to fix this problem. Someone will need to develop alternatives, like ULID.

I've considered adding ULIDs to this library, but since other libraries exist that provide them, it hasn't been a priority.

**Comment by donnysim** [comment]
@ramsey other implementations of ULID don't support binary, so maybe there's a chance you'd want to re-evaluate adding ULID support? I trust your implementations more than the others 😅
