### ISSUE TITLE
Possibility to use PHP8.1

### ISSUE THREAD

**Issue by zmitic** [ramsey/uuid#393]
## How do I use constructor instead of static methods?

I am aware it it not possible now but is it something that can be build in future, or there is a fork with that possibility?

## Example code
Use case for Doctrine entity and PHP8.1 (new in initializers):

```php
class Product
{
    public function __construct(
        private string $name,
     
        private UuidInterface $id = new Uuid4(),     // id is generated if not provided
    ){}     

    public function getId(): UuidInterface           // it is never null
    {
        return $this->id;
    }
}
```

**Comment by mpyw** [comment]
The `Uuid` class requires dependency injection to keep its implementation clean. Given that intent, it is not recommended to use instance creation as the default argument.

However, if you want to interoperate with Doctrine, you can pack the factory method calls into a wrapper class constructor. Also, it would be preferable to wrap the `UuidFactory` class as a singleton.

It looks pretty messy but it would be necessary if you want to abandon "Simple" and go for an "Easy" implementation.

```php
class SingletonUuidFactory extends UuidFactory
{
    private static ?self $instance = null;

    private function __construct()
    {
        parent::__construct();
    }

    public static function getInstance(): self
    {
        if (!$this->instance) {
            $this->instance = new self();
        }
        return $this->instance;
    }
}

class FactoriableUuid4 extends Uuid
{
    private UuidInterface $id;

    public function __construct(
        ?UuidInterface $id = null,
        ?UuidFactoryInterface $factory = null,
    )
    {
        if (!$id) {
            $factory ??= SingletonUuidFactory::getInstance();
            $id = $factory->uuid4();
        }
        $this->id = $id;
    }

    public function getId(): UuidInterface
    {
        return $this->id;
    }
}
```

See also: https://stackoverflow.com/questions/10330704/symfony-2-0-getting-service-inside-entity/32851695#32851695

**Comment by mpyw** [comment]
The `Uuid` class requires dependency injection to keep its implementation clean. Given that intent, it is not recommended to use instance creation as the default argument.

However, if you want to interoperate with Doctrine, you can pack the factory method calls into a wrapper class constructor. Also, it would be preferable to wrap the `UuidFactory` class as a singleton.

```php
final class SingletonUuidFactory extends UuidFactory
{
    private static ?self $instance = null;

    public static function getInstance(): self
    {
        if (!$this->instance) {
            $this->instance = new self();
        }
        return $this->instance;
    }
}

class FactoriableUuid4
{
    private UuidInterface $id;

    public function __construct(
        ?UuidInterface $id = null,
        ?UuidFactoryInterface $factory = null,
    )
    {
        if (!$id) {
            $factory ??= SingletonUuidFactory::getInstance();
            $id = $factory->uuid4();
        }
        $this->id = $id;
    }

    public function getId(): UuidInterface
    {
        return $this->id;
    }
}

class Product
{
    public function __construct(
        private string $name,
        private UuidInterface|FactoriableUuid4 $id = new FactoriableUuid4(),
    ){}     

    public function getId(): UuidInterface 
    {
        return $this->id instanceof UuidInterface
            ? $this->id
            : $this->id->getId();
    }
}
```

It looks so messy but it would be necessary if you want to abandon "Simple" and go for an "Easy" implementation.

See also: https://stackoverflow.com/questions/10330704/symfony-2-0-getting-service-inside-entity/32851695#32851695

**Comment by zmitic** [comment]
Thank you, I think I will hold :smile:

**Comment by ramsey** [comment]
Thanks, @mpyw.

@zmitic, a wrapper class is definitely the way to go here. Best of luck!
