### ISSUE TITLE
Sequential UUIDs

### ISSUE THREAD

**Issue by ghola** [ramsey/uuid#40]
Any plans for COMBs?
http://en.wikipedia.org/wiki/Globally_unique_identifier#Sequential_algorithms
http://www.codeproject.com/Articles/388157/GUIDs-as-fast-primary-keys-under-multiple-database
http://www.informit.com/articles/article.aspx?p=25862

**Comment by ramsey** [comment]
Implemented in #43. Closing out this issue.
