### ISSUE TITLE
Uuid->getBytes() sometimes generated 14 instead of 16 bytes

### ISSUE THREAD

**Issue by vedran-korponajic** [ramsey/uuid#400]
I'm having a problem in getting the UUID from the database, in which I'm storing it as CHAR(16). I populated some upcoming orders with the UUID using $uuid->getBytes(), and for the most part it populates it okay, but for some reason, there are a couple of fields where the uuid saved is 14 characters instead of 16.

<img width="739" alt="Screen Shot 2022-01-26 at 8 59 53 PM" src="https://user-images.githubusercontent.com/43841707/151237732-9a41f6e4-fe78-48b5-9809-cd0e65078e64.png">

I'm not sure how to reproduce this because for most of them it's correct, 16 but for some it's 14 and I have no idea why. Because of this, I'm getting an error: Fatal error: Uncaught Ramsey\Uuid\Exception\InvalidArgumentException: $bytes string should contain 16 characters. in vendor/ramsey/uuid/src/Codec/StringCodec.php on line 95

**Comment by vedran-korponajic** [comment]
Just did a query in the database and I can see that there are fields with 13,14,15 characters instead of 16, so there is deeper problem here I'm guessing.

**Comment by vedran-korponajic** [comment]
Oh, and I'm using Uuid::uuid4() to generate the uuid variable, and then calling getBytes() from that variable.

**Comment by ramsey** [comment]
Hi!

Can you share more details about the database you're using, e.g., name and version?

Also, can you share the relevant portions of the `CREATE TABLE` statement? I'm interested in the definition for this column and also for the database engine type.

**Comment by vedran-korponajic** [comment]
Hi, sure.

I'm using MySQL 80.0.21, InnoDB, default charset is UTF-8

This is the query I used to add the field
`ALTER TABLE orders ADD COLUMN uuid CHAR(16) DEFAULT NULL`

**Comment by vedran-korponajic** [comment]
@ramsey Generated the UUID a couple thousand times, found that the issue is actually happening while the string is saved in out DB, we'll sort it out internally. Sorry for wasting your time, wish you a great weekend!

**Comment by ramsey** [comment]
No worries. Glad you were able to figure out where the issue is happening.

**Comment by ramsey** [comment]
Thanks for following up, and I'm glad you found the issue!

Can you share the `CHARSET` for the table? That might help explain what's going on.

**Comment by vedran-korponajic** [comment]
The charset is utf-8.

**Comment by willemstuursma** [comment]
The problem is using the `CHAR` column type instead of the `BINARY` column type, which should be used for binary data in MySQL.
