### ISSUE TITLE
Unable to go on https://uuid.ramsey.dev/ for documentation

### ISSUE THREAD

**Issue by ghost** [ramsey/uuid#409]
Hi,

Unable to go https://uuid.ramsey.dev/
Need to access to the doc.

Thank you

**Comment by ramsey** [comment]
Are you still unable to load the documentation site?

**Comment by ghost** [comment]
Still unable to load web site documentation i get "This site can’t be reached"

**Comment by ramsey** [comment]
It's hosted by Read the Docs. Are you able to reach https://readthedocs.org ?

**Comment by ghost** [comment]
Yes but now able to reach https://readthedocs.org/ and https://uuid.ramsey.dev/ thank you :)
