### ISSUE TITLE
Incompatible with brick/math: 0.8.0. Error: Call to undefined method Brick\Math\BigInteger::fromBase()

### ISSUE THREAD

**Issue by jojoguru** [ramsey/uuid#423]
## Description
Method getInteger() of UuidInterface throws Exception when lowest possible version of `brick/math` is installed
Version constraint `"brick/math": "^0.8 || ^0.9"` is incorrect. At least version **4.2.x** & **4.3.x** of `ramsey/uuid` depend on `brick/math >= 0.8.8`.

## Steps to reproduce
1. install package via `composer require ramsey/uuid`
2. install lowest versions via `composer update --prefer-lowest`
3. call `Uuid::uuid4()->getInteger();`

## Expected behavior
Should return an `Ramsey\Uuid\Type\Integer` instead of crashing.

## Screenshots or output
```
Error : Call to undefined method Brick\Math\BigInteger::fromBase()
 /example/vendor/ramsey/uuid/src/Math/BrickMathCalculator.php:104
 /example/vendor/ramsey/uuid/src/Converter/Number/GenericNumberConverter.php:48
 /example/vendor/ramsey/uuid/src/Uuid.php:359
 /example/vendor/ramsey/uuid/src/Lazy/LazyUuidFromString.php:264
```

## Environment details
- version of this package: `4.2.0`, `4.3.0`
- PHP version: `7.4.26`, `8.0.13`, `8.1.7`

## Additional context
After looking in the brick/math sources, the missing method Brick\Math\BigInteger::fromBase() was added in version 0.8.8.
Adjusting the version constraint of `brick/math` to  `"^0.8.8 || ^0.9"` should fix the problem.

**Comment by ramsey** [comment]
Thanks for the report! Addressed in 928a62c7152da3e8f9e35c211407d783f328b757.
