### ISSUE TITLE
Pls update dependency of brick/math to latest v 0.10

### ISSUE THREAD

**Issue by palansher** [ramsey/uuid#433]
Thanks for the great product!

Would you pls update deps due to latest "brick/money" requires the latest brick/math (0.10)

The current ramsey/uuid supports only  "brick/math": "^0.8 || ^0.9"

https://github.com/brick/math 

PS: sorry for "bug" category - others also not too much suitable :)

**Comment by Hesesses** [comment]
Cant update to laravel 9 because of this 😓

**Comment by willemstuursma** [comment]
See #427

**Comment by ramsey** [comment]
Thanks for the report. Please upgrade to version 4.4.0, which supports brick/math 0.10.
