### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by snyderpa-owl** [ramsey/uuid#464]
Continue to support php 7 for the 4.x major release cycle

## Background/problem

In the release for 4.5.0 (a minor version change) the code for `/uuid/src/Uuid.php` fails `php -l Uuid.php` on php 7.3
This causes code defined with a 4.x dependence to fail under php version 7.3 (for example)
## Proposal/solution

Delay introduction of php 8 specific type hinting to a major release
## Alternatives

As a workaround, consumers who are unable to updgrade php to 8 will have to freeze this project at 4.4.0

**Comment by ramsey** [comment]
As of version 4.3.0, I dropped support for PHP 7. See here: https://github.com/ramsey/uuid/releases/tag/4.3.0

This is not a BC break, since Composer will do the right thing for your environment and select a compatible version of this library.

How did you install version 4.5.0 on PHP 7.3? Composer should not have allowed this—it should have automatically installed ramsey/uuid 4.2.3 instead.

**Comment by snyderpa-owl** [comment]
snipped from composer.json
```
  "require": {
    "php": ">=7.0.0",
    "ramsey/uuid": "^4.0"
  },
```
snipped from docker-compose.yml
```
  composer-update-api:
    image: composer:2
    volumes:
      - ./api:/var/www/api
    working_dir: /var/www/api
    entrypoint: [ 'composer', 'update', '--ignore-platform-reqs' ]
```

**Comment by ramsey** [comment]
With that configuration, when you run `composer install` on a system running PHP 7.3, it should install ramsey/uuid version 4.2.3. Can you confirm that you are running PHP 7.3 on the same system where you run `composer install`?

**Comment by snyderpa-owl** [comment]
I have confirmed that the issue is due to using a composer:2 docker image that is running php 8 to install dependencies to run in a  php:7.3-fpm-bullseye container.  Thank you for your prompt assistance.

**Comment by snyderpa-owl** [comment]
Install docker
Make a directory "proof"
Create a file `composer.json`
```
{
    "name": "ramsey/proof",
    "description": "Prove accurate composer",
    "require": {
        "ramsey/uuid": "^4.0"
    }
}
```
Create a file `docker-compose.yml`
```
version: '3.8'

services:

  composer-update-api:
    image: composer:2.0.8
    container_name: composer-api
    volumes:
      - ./:/var/www/owloutcomes/api
    working_dir: /var/www/owloutcomes/api
    entrypoint: [ 'composer', 'update', '--ignore-platform-reqs' ]
```
From a command-line terminal
```
$ docker-compose run --rm --entrypoint "php --version" composer-update-api
Creating network "proof_default" with the default driver
Creating proof_composer-update-api_run ... done
PHP 7.4.14 (cli) (built: Jan 15 2021 23:17:24) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```
Observe php version is 7.4.14
Use composer docker image to install the ramsey/uuid dependency
```
$ docker-compose up composer-update-api                                   
Creating composer-api ... done
Attaching to composer-api
composer-api           | Loading composer repositories with package information
composer-api           | Info from https://repo.packagist.org: #StandWithUkraine
composer-api           | Updating dependencies
composer-api           | Lock file operations: 4 installs, 0 updates, 0 removals
composer-api           |   - Locking brick/math (0.10.2)
composer-api           |   - Locking ramsey/collection (1.2.2)
composer-api           |   - Locking ramsey/uuid (4.5.1)
composer-api           |   - Locking symfony/polyfill-php81 (v1.26.0)
composer-api           | Writing lock file
composer-api           | Installing dependencies from lock file (including require-dev)
composer-api           | Package operations: 4 installs, 0 updates, 0 removals
composer-api           |   - Downloading symfony/polyfill-php81 (v1.26.0)
composer-api           |   - Downloading ramsey/collection (1.2.2)
composer-api           |   - Downloading brick/math (0.10.2)
composer-api           |   - Downloading ramsey/uuid (4.5.1)
composer-api           |  0/4 [>---------------------------]   0%
composer-api           |  1/4 [=======>--------------------]  25%
composer-api           |  3/4 [=====================>------]  75%
composer-api           |  4/4 [============================] 100%  - Installing symfony/polyfill-php81 (v1.26.0): Extracting archive
composer-api           |   - Installing ramsey/collection (1.2.2): Extracting archive
composer-api           |   - Installing brick/math (0.10.2): Extracting archive
composer-api           |   - Installing ramsey/uuid (4.5.1): Extracting archive
composer-api           |  0/4 [>---------------------------]   0%
composer-api           |  1/4 [=======>--------------------]  25%
composer-api           |  2/4 [==============>-------------]  50%
composer-api           |  3/4 [=====================>------]  75%
composer-api           |  4/4 [============================] 100%5 package suggestions were added by new dependencies, use `composer suggest` to see details.
composer-api           | Generating autoload files
composer-api           | 4 packages you are using are looking for funding.
composer-api           | Use the `composer fund` command to find out more!
composer-api exited with code 0
```
Observe that package-lock is created with message "Locking ramsey/uuid (4.5.1)"

**Comment by ramsey** [comment]
You're using `--ignore-platform-reqs` which turns off Composer's ability to limit packages based on platform requirements.

For example, these are the dependencies for version 4.5.1:

https://github.com/ramsey/uuid/blob/a161a26d917604dc6d3aa25100fddf2556e9f35d/composer.json#L11-L17

Using `--ignore-platform-reqs` instructs Composer to ignore the `^8.0` requirement for PHP.

**Comment by snyderpa-owl** [comment]
Yes, `--ignore-platform-reqs` will be necessary to maintain the legacy.  Solution for this case will be to pin the dependency at 4.2.3 -- thanks again.
