### ISSUE TITLE
Validation failing for empty values

### ISSUE THREAD

**Issue by christiaan-lombard** [ramsey/uuid#47]
Unless I am missing something, most rules should not be validated (or validation should return true) if the input is null or an empty string (except for Required, Length and some others).

There are likely more rules failing for empty values, but the ones I found are:

 - Alpha
 - AlphaNumHyphen
 - AlphaNumeric

**Comment by ramsey** [comment]
Can you please provide an example and describe the expected output contrasted with the actual output? Thanks!

**Comment by christiaan-lombard** [comment]
apologies, issue is intended for siriusphp/validation
