### ISSUE TITLE
Larevel 9 error forgot password "Class "Ramsey\Uuid\Converter\Time\UnixTimeConverter" not found"

### ISSUE THREAD

**Issue by F3nrihr** [ramsey/uuid#471]
Larevel 9 error forgot password "Class "Ramsey\Uuid\Converter\Time\UnixTimeConverter" not found"

Hello. 
I'm having a problem with laravel 9 password recovery with jetstream/fortify (Recover password by using a form and sending an email with a link to create a new password). I have pulled it to a modal but I keep pointing to the url route('password.email') with post method.But I get this error: Error Class "Ramsey\Uuid\Converter\Time\UnixTimeConverter" not found enter image description here

I have checked that I have "ramsey/uuid": "^4.5". In the database I see that password_resets changes the token.
<img width="879" alt="Captura de Pantalla 2022-10-28 a las 10 52 35" src="https://user-images.githubusercontent.com/18676406/198578852-b8de78f7-2908-47a1-8857-9f8b453ca950.png">

I am at a loss as to what the error could be.

**Comment by F3nrihr** [comment]
Removing composer.lock and vendor and reinstalling has been the solution.

**Comment by ramsey** [comment]
Good to hear you were able to resolve this. 👍🏻
