### ISSUE TITLE
Could not find branch v5.x-dev anymore

### ISSUE THREAD

**Issue by chadyred** [ramsey/uuid#482]
Hello, your branch v5 has suddenly dissappeay but it fix issues about interface and php 8.1.

Any news about it @ramsey ?

Thnaks your work

**Comment by ramsey** [comment]
The 4.x branch had gotten so far ahead of the 5.x branch that I dropped the branch, thinking I would start a new 5.x branch later.

I've just restored the 5.x branch and have merged 4.x into it and resolved all the conflicts, so it's now up-to-date.

Were you using the 5.x branch? It's very unstable, so I would not advise using it.

**Comment by chadyred** [comment]
Alright thanks for your reply, and of course, I will not used it anymore :pray:

**Comment by chadyred** [comment]
@ramsey And for you question:  I used it because of the error from php 8.1 and the serialize / unserialize method deprecated from your `UuidInterface`. It seems that you solve it in your branch 5, this is why I use it

**Comment by ramsey** [comment]
You might see those deprecation messages when using version 4 of ramsey/uuid, but they're not errors. 😄

**Comment by chadyred** [comment]
Yes  ! But PhpSpec didn't like that, and associate deprecation message as errors :thinking:
