### ISSUE TITLE
ramsey/collection dependency requires PHP 8.1.

### ISSUE THREAD

**Issue by QuietNoise** [ramsey/uuid#489]
Hi,

One of your dependencies 'ramsey/collection' now requires PHP 8.1 making ramsey/uuid 4.7 not installing on platforms set to use PHP 8.0 and downgrading them to ramsey/uuid 3.9.7.

## Steps to reproduce
1. run  `composer require ramsey/uuid` on composer project that's configured to run on PHP 8.0 (i.e. composer.json has 
`"config": {
    "platform": {
      "php": "8.0"
    }
  }`
2. observe that installed  ramsey/uuid  version is 3.9.7 instead of ^4.7. If ramsey/uuid was installed previously it will be downgraded as well.

## Expected behavior
Command `composer require ramsey/uuid` on platforms configured for PHP 8.0 should install version 4.7 as was normally the case previously before ramsey/collection was updated to 2.0.

## Environment details
- version of this package: 4.7.3
- PHP version: 8.0 / 8.1
- OS: Windows 10

**Comment by ramsey** [comment]
ramsey/collection 2.0 requires PHP 8.1, but ramsey/uuid allows versions `^1.2 || ^2.0` of ramsey/collection. It sounds like you might have another dependency that's causing problems.

**Comment by QuietNoise** [comment]
Thank for checking it out. I can confirm that running composer `require ramsey/uuid` on a fresh project i.e. like this:
```
{
  "name": "uuid/test",    
  "config": {
    "platform": {
      "php": "8.0"
    }
  },
}
```
will install version 4.7.3. 
While on my project which is saturated with bunch of other dependencies it will either install or downgrade to 3.9 (not sure why), I can get away with forcing installing a particular version like by running `composer require ramsey/uuid ^4.7.3`.
Case closed I guess.
