### ISSUE TITLE
Remove the deleted tag in packagist.org

### ISSUE THREAD

**Issue by BadJacky** [ramsey/uuid#497]
Hi @ramsey 

I use this package in my prod environment, it is a great package.

Recently I found there is a dev version in packagist but not in the github tags and releases.

I think you may forget to remove the dev version in packagist.

Could you remove the [4.x-dev](https://packagist.org/packages/ramsey/uuid#4.x-dev) in packagist.org?

I have attached the screenshot files and hope they can help you.

Thanks!
<img width="1276" alt="Screenshot 2023-02-23 at 09 31 49@2x" src="https://user-images.githubusercontent.com/113529280/220869201-a39e7cae-c403-4090-9831-cec703b23993.png">

<img width="1256" alt="Screenshot 2023-02-23 at 09 31 41@2x" src="https://user-images.githubusercontent.com/113529280/220869209-20334278-8511-4239-8589-9dac67fa941b.png">

<img width="1341" alt="Screenshot 2023-02-23 at 09 31 25@2x" src="https://user-images.githubusercontent.com/113529280/220869227-03cf874a-8eba-453d-b227-51efcc8739ba.png">

**Comment by ramsey** [comment]
`4.x-dev` is how Composer references the `4.x` branch.

See this article for more information: https://getcomposer.org/doc/articles/versions.md#branches

**Comment by BadJacky** [comment]
Thanks for your reply!

I have locked this package's version in the root composer.json under my project.

**Comment by ramsey** [comment]
Were you seeing errors about `4.x-dev` missing? Why did you need to lock the package version in `composer.json`?
