### ISSUE TITLE
Uuid v7 collisions

### ISSUE THREAD

**Issue by vudaltsov** [ramsey/uuid#518]
## Description

From time to time I get v7 collisions. I also noticed that since https://github.com/ramsey/uuid/commit/0ba1ffb0297f3d4d15dfadd739b1b040361ba91b uuids of this version do not differ much in the random part, maybe, that's the reason?

## Steps to reproduce
```php
<?php

// generate_uuids_v7.php

use function Ramsey\Uuid\v7;

require_once __DIR__.'/vendor/autoload.php';

for ($j = 0; $j < 100; ++$j) {
    $uuids = '';

    for ($i = 0; $i < 1_000_000; ++$i) {
        $uuids .= v7()."\n";
    }

    file_put_contents('uuids_v7.txt', $uuids, $j === 0 ? 0 : FILE_APPEND);
}
```
```shell
php generate_uuids_v7.php && sort uuids_v7.txt | uniq -cd
```

## Expected behavior
Empty output

## Screenshots or output

```
   2 018b2847-0e47-7148-8dec-df216b0d76c7
   2 018b2847-a950-7367-9fa7-e3344774c890
   2 018b2847-c3b4-7203-be93-5976ad423647
   2 018b2847-fbbd-703e-b616-d256da1f0ec0
   2 018b2848-1f15-7200-b831-ddc7c0e6f86f
   2 018b2848-dcbf-72eb-b6ea-256c9e1f5d38
```

## Environment details

- version of this package: 4.7.4
- PHP version: 8.2.10
- OS: macOS Ventura (13.3.1)

**Comment by vudaltsov** [comment]
Running same code with `"ramsey/uuid": "4.5.1"` does not give any collisions. So the bug is in new `UnixTimeGenerator`.

**Comment by ramsey** [comment]
The new code in `UnixTimeGenerator` was mostly borrowed from [symfony/uid](https://symfony.com/doc/current/components/uid.html). Can you reproduce the issue using their method for generating v7 UUIDs?

**Comment by vudaltsov** [comment]
> Can you reproduce the issue using their method for generating v7 UUIDs?

Yes, done.

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/pull/52367 for the fix

**Comment by ramsey** [comment]
Thanks, @nicolas-grekas!

**Comment by vudaltsov** [comment]
I will do a PR.

**Comment by fannyfan414** [comment]
@ramsey @nicolas-grekas Hi! Have a question about `uuid v7` collisions.

I need to **replace 4-5 chars** after generation uuid v7 with **my specific characters** (servers id or smth else).
At what positions would you advise me to change them so as not to greatly increase the chance of collisions?

**Comment by vudaltsov** [comment]
@fannyfan414 , you can use UUID v8, it allows to put arbitrary content.

**Comment by ramsey** [comment]
I would recommend using UUIDv8 for your use-case, by the way. It's intended for custom layouts like the one you're using.

To minimize chance of collision, I would probably place the server ID in the bytes to the far right of the UUID layout.
