### ISSUE TITLE
How can I integrate this library with CodeIgniter?

### ISSUE THREAD

**Issue by maxxon15** [ramsey/uuid#54]
Okay, this is not an "issue" as per se, but rather a question.

How can I integrate this with CodeIgniter?

1. I included this inside the **application/third_party** folder in CodeIgniter.
2. Ran composer there to include all the dependencies.
3. I also made another file named **uid.php** in the **application/libraries** folder, where I wrote the following code:

```php
<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

require_once APPPATH."third_party/uuid/vendor/autoload.php";

use Rhumsaa\Uuid\Uuid;
use Rhumsaa\Uuid\Exception\UnsatisfiedDependencyException;

?>
```

4. But, when I try out the sample code inside a Controller file's **index()** function just to try it out, it says

```
( ! ) Fatal error: Class 'Uuid' not found in /var/www/public/application/controllers/login.php on line 18
Call Stack
#	Time	Memory	Function	Location
1	0.0001	242688	{main}( )	.../index.php:0
2	0.0009	244688	require_once( '/var/www/public/system/core/CodeIgniter.php' )	.../index.php:202
3	0.0314	664784	call_user_func_array:{/var/www/public/system/core/CodeIgniter.php:360} ( )	.../CodeIgniter.php:360
4	0.0314	665048	Login->index( )	.../CodeIgniter.php:360
```

I'm not even sure I'm doing something wrong.
How can I include this library? Please help! :)

**Comment by aztech-dev** [comment]
Instead of running `composer install` in the uuid folder, you should install the library using composer (don't download/install manually like you did), something like:

```bash
cd application/thirdparty
composer require rhumsaa/uuid
```

Then from your autoload file in CodeIgniter, include the vendor autoload file:

```php
require_once APPPATH."third_party/vendor/autoload.php";
```

Have a look at http://stackoverflow.com/questions/13741917/how-to-use-composer-packages-in-codeigniter also.

**Comment by lynxtdc** [comment]
Have you tried renaming the file you created in application/libraries Uuid.php?  Just a thought after quick review of the above.

**Comment by harikt** [comment]
My assumption is from controller `/var/www/public/application/controllers/login.php` may be you should try 

```
use Rhumsaa\Uuid\Uuid;
use Rhumsaa\Uuid\Exception\UnsatisfiedDependencyException;
```

Thanks

**Comment by aztech-dev** [comment]
:+1: for @harikt 's assumption (but you should *still* install the package using composer, not manually)

**Comment by harikt** [comment]
I have not worked with codeignitter. But using composer is dead simple in any project via editing the file you know which will load always. 

Eg : `web/index.php` , `public/index.php` and adding the line `require '/path/to/vendor/autoload.php'` .

Yey everything works fine ;) .

**Comment by maxxon15** [comment]
@harikt 's solution worked perfectly! :) Thanks.

But isn't including files like that considered a bad practice in CodeIgniter?

I've heard people always recommend to use the load function to load classes and libraries. It would have been great if I could have been able to do it that way...

Like this:

```php
$this->load->library('classname');
$this->load->helper('classname'); // This is a helper class
```

**Comment by harikt** [comment]
@maxxon15 Codeignitter itself is rejected by community . So I wonder what the best practice is.

Thanks!

**Comment by maxxon15** [comment]
@harikt LOL! Well that's true. :+1: :laughing:
