### ISSUE TITLE
Versions and namespaces

### ISSUE THREAD

**Issue by arvidbjorkstrom** [ramsey/uuid#59]
When I run `composer require ramsey/uuid` composer gives me the 2.8 version of the library, and then the rest of the instructions on the main page aren't correct - the namespace for 2.8 is still `Rhumsaa\Uuid`. Either change the instructions on the frontage or change the namespaces in the 2.8 branch.

```
composer require ramsey/uuid:~3.0@dev
```
Would do the trick.

**Comment by ramsey** [comment]
The 2.8 version is the stable version, while 3.0 (master branch) is still in flux, so there is not yet a release for it. I do not wish to encourage others to upgrade to a dev version whose API could change from one day to the next.

The 2.8 branch is solid and stable, and the README instructions there are correct.

**Comment by arvidbjorkstrom** [comment]
Then maybe set the 2.8 branch as the default one in github?

**Comment by ramsey** [comment]
I forgot I could do that. Thanks for the reminder. Done! :-)
