### ISSUE TITLE
Examples issue

### ISSUE THREAD

**Issue by n0th1n9** [ramsey/uuid#64]
use Rhumsaa\Uuid\Uuid;   should be change to use Ramsey\Uuid\Uuid;

**Comment by ramsey** [comment]
In the 2.8 branch, it should remain Rhumsaa\Uuid\Uuid. In the master branch, it should be Ramsey\Uuid\Uuid. Which branch are you looking at?

**Comment by n0th1n9** [comment]
3.0@dev

**Comment by ramsey** [comment]
Can you link to the specific line where you see this? I can't find it anywhere in the master branch.

**Comment by zackshapiro** [comment]
I'm having this same issue with 2.8. 

Using 

```php
use Rhumsaa\Uuid\Uuid;
use Rhumsaa\Uuid\Exception\UnsatisfiedDependencyException;
```
Worked using version 2.8, wrote a note for myself to upgrade to `Ramsey\` when 3.0 is done

**Comment by barryvdh** [comment]
Same here, just pulled in latest stable with Composer. Example doesn't match the latest version (2.8.1)

**Comment by TomasVotruba** [comment]
PR anybody?

**Comment by ramsey** [comment]
There doesn't need to be a PR for this. The README in the master branch is correct.

I have set the default branch on GitHub to 2.8. Does this resolve the issue?

**Comment by barryvdh** [comment]
yes, thanks!

**Comment by TomasVotruba** [comment]
:+1:

**Comment by ramsey** [comment]
Note: related to #65 and #66.
