### ISSUE TITLE
default version 2.8.1 from "composer require ramsey/uuid" still need use Rhumsaa\Uuid\Uuid;

### ISSUE THREAD

**Issue by timhaak** [ramsey/uuid#66]
Hi 

One the main page says use "composer require ramsey/uuid" which pulls in 2.8.1 which still needs.

use Rhumsaa\Uuid\Uuid;

The readme for 2.8.1 is correct. Just the steps on master aren't yet.

**Comment by ramsey** [comment]
Thanks for using the library and your interest in contributing.

The namespace is changing in version 3.0.0. Master represents 3.0.0-dev, so it is correct.

**Comment by timhaak** [comment]
Cool :) Thanks for the libary
