### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by mindplay-dk** [ramsey/uuid#71]
Very minor issue, but you should maybe set the default branch (on GitHub) to master? - it's pretty confusing, arriving here from packagist, the title on the landing page header matches the new package name, but the README below is screaming "this package is deprecated!". I was on the GitHub page twice this week before I realized it doesn't default to the master branch ;-)

**Comment by aztech-dev** [comment]
This is due to #64 . Once 3.0 is released, the default branch can probably be reverted to master...

**Comment by ramsey** [comment]
Oops! I recently merged rhumsaa/uuid 2.8.2 into this 2.8 branch, and it has all the deprecation warnings in the README. For a short-term fix, I'll update the README here today. Near-term, I'll be releasing 3.0 and defaulting to the master branch soon.

Sorry for the confusion.

**Comment by ramsey** [comment]
I removed the warning message from the README. See 1c01dec0c4f71e682c540c36e0d00453a4dcd3f3

**Comment by lorenzomar** [comment]
Hello @ramsey, are you able to indicate a date for 3.0 release?
Thanks

**Comment by ramsey** [comment]
Soon? :-)

I've been swamped, so it's been difficult to devote time to wrapping things up. In my mind the only major things left are:

* Docblocks for everything
* Improved code coverage

Once I make headway on these items, then I'll be comfortable cutting a beta, writing some "upgrade" documentation, and then releasing a GA.
