### ISSUE TITLE
Tests fail on 32 bit systems without Moontoast/BigNumber

### ISSUE THREAD

**Issue by aztech-dev** [ramsey/uuid#76]
When running the test suite on a 32-bit system with Moontoast/BigNumber install, one of the tests fail due to an exception message mismatch (~~which should not even be thrown~~ the failing test is actually one that simulates the absence of Moontoast): 

```
PHPUnit 4.8.3 by Sebastian Bergmann and contributors.
Warning:	The Xdebug extension is not loaded
		No code coverage will be generated.

........... .........................SSSSSSSSSSSSSSSSSSSSSSSSSSS  63 / 184 ( 34%)
SSSSSSSSSSSSSSSSSSSSSS...............S........S....S....S...... 126 / 184 ( 68%)
..........S...................SS.SS......................F

Time: 48.99 seconds, Memory: 6.25Mb

There was 1 failure:

1) Rhumsaa\Uuid\UuidTest::testGetInteger
Failed asserting that exception message 'When calling Rhumsaa\Uuid\Uuid::calculateUuidTime on a 32-bit system, Moontoast\Math\BigNumber must be present in order to generate version 1 UUIDs' contains 'Cannot call Rhumsaa\Uuid\Uuid::getInteger without support for large integers'.

FAILURES!
Tests: 184, Assertions: 1830, Failures: 1, Skipped: 58.
```

```
root@debian:~/uuid# cat composer.lock | grep moontoast
            "name": "moontoast/math",
                "url": "https://github.com/ramsey/moontoast-math.git",
                "url": "https://api.github.com/repos/ramsey/moontoast-math/zipball/fce28a9d1e73e73376cb44e5e581675d15fbe2f3",
            "homepage": "https://github.com/moontoast/math",
```

**Comment by ramsey** [comment]
I wish we could run 32-bit tests on Travis to catch these, but it looks like they don't plan on supporting that: https://github.com/travis-ci/travis-ci/issues/986

**Comment by aztech-dev** [comment]
Yup, I caught that while trying to run the testsuite on an emulator to get a big-endian platform.

Also this affects both 2.8.x (haven't checked previous releases) and 3.x

**Comment by ramsey** [comment]
Very some reason, I missed your pull requests and have just now merged them in. Sorry about that.

Please run your tests again and confirm that tests pass on `2.8` and `master`. Thanks!

**Comment by aztech-dev** [comment]
No worries. Tests are all good after merge on both 2.8.x and master.
