### ISSUE TITLE
Can I remove hyphens from the result of Uuid::uuid4()?

### ISSUE THREAD

**Issue by RealLeooo** [ramsey/uuid#84]
Is it still unique? 
What's the function of hyphens?
Because sometimes I want store a 32-byte uuid.

**Comment by aztech-dev** [comment]
Hyphens only exist in the string representation of a UUID, and removing them has no effect. They are only used to help humans read UUIDs. "df23a20d-fa65-4933-a760-f3a3ab210079" is *exactly* the same as "df23a20dfa654933a760f3a3ab210079".

However, I'm not too sure about what you mean by 32-bit UUID. Those do not exist (a UUID is 128-bits, no less), and the chance of getting collisions with only 32 bits is much higher.

**Comment by RealLeooo** [comment]
I am sorry, it is 32-byte. Thanks a lot!
