### ISSUE TITLE
Collisions occurring in COMB sequential UUID test

### ISSUE THREAD

**Issue by ramsey** [ramsey/uuid#86]
The presence of Xdebug appears to slow things down significantly enough that COMB sequential UUIDs generated during tests have no collisions, but if tests run in an environment without Xdebug, then tests will almost always produce duplicate COMB UUIDs.

To reproduce (using a VirtualBox VM with Vagrant):

    git clone https://github.com/ramsey/uuid.git
    cd uuid/
    vagrant init ubuntu/trusty64
    vagrant up
    vagrant ssh
    cd /vagrant
    sudo apt-get install php5 php5-curl
    curl -sS https://getcomposer.org/installer | php
    ./composer.phar install
    ./vendor/bin/phpunit --verbose

You will see a consistent test failure like this:

    1) Ramsey\Uuid\UuidTest::testUuid4Comb
    Failed asserting that '30303030-3030-4030-b030-8351f882227f' is greater than '30303030-3030-4030-b030-8351f8822280'.

    /vagrant/tests/UuidTest.php:839

Now, install Xdebug and run the test again:

    sudo apt-get install php5-xdebug
    ./vendor/bin/phpunit --verbose

Tests will consistently pass.

Remove Xdebug, and tests consistently fail again:

    sudo apt-get remove php5-xdebug
    ./vendor/bin/phpunit --verbose

We need to revisit COMB generation to see what can be done to ensure consistent, sequential UUIDs.

**Comment by aztech-dev** [comment]
Interesting. I'm not getting that behavior at all, with or without XDebug. May be related to the performance of the machine on which the tests are running:

```
thibaud@thibaud:uuid$ sudo php5enmod xdebug
thibaud@thibaud:uuid$ phpunit
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

Configuration read from uuid/phpunit.xml.dist

........S......................................................  63 / 109 ( 57%)
......................................S.......

Time: 3.94 minutes, Memory: 13.00Mb

OK, but incomplete, skipped, or risky tests!
Tests: 109, Assertions: 67397, Skipped: 2.

Generating code coverage report in Clover XML format ... done

Generating code coverage report in HTML format ... done
thibaud@thibaud:uuid$ sudo php5dismod xdebug
thibaud@thibaud:uuid$ phpunit
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

Configuration read from uuid/phpunit.xml.dist

The Xdebug extension is not loaded. No code coverage will be generated.

........S......................................................  63 / 109 ( 57%)
......................................S.......

Time: 5.07 seconds, Memory: 7.00Mb

OK, but incomplete, skipped, or risky tests!
Tests: 109, Assertions: 67397, Skipped: 2.
```

Regarding the collisions you report, I'm not sure you can call them critical. In the test environment, a static random generator is used, which always returns the same "0" padded string (https://github.com/ramsey/uuid/blob/master/tests/src/UuidTest.php#L831). In real world environments, you'll be using a real random source, which ensures that even if the time-part is the same for two UUID's, the remaining bytes are random, cancelling out the collision.

A simple fix would be to sleep for [0.00001 seconds](https://github.com/ramsey/uuid/blob/master/src/Generator/CombGenerator.php#L83) in the test before generating a new COMB UUID.

A better fix would be to be able to mock the time source, unfortunately, I'm not aware of any feature of PHP that would let us do that easily. It's also possible to abstract away the time source, but that would mean yet another abstraction layer.

**Comment by ramsey** [comment]
I thought about the sleeping, too.

Admittedly, I could not reproduce on my host OS (Mac Yosemite) with PHP without Xdebug.

**Comment by aztech-dev** [comment]
Another point that strikes me is the reported failure:

```
1) Ramsey\Uuid\UuidTest::testUuid4Comb
Failed asserting that '30303030-3030-4030-b030-8351f882227f' is greater than '30303030-3030-4030-b030-8351f8822280'.

/vagrant/tests/UuidTest.php:839
```

Had it been a collision, the two UUIDs should have been equal. Here it looks like the UUID that was generated last actually has a lower timestamp than the first one. Could it be that there is some clock skewing going on in the VM (just a wild guess, trying to find a plausible explanation for the second timestamp being earlier than the first one) ?

**Comment by ramsey** [comment]
That's funny. I didn't notice how odd that failure looked. All the earlier failures I noticed appeared to be equal UUIDs (collisions).

**Comment by Xerkus** [comment]
Isn't COMB idea not to have half sequential and another half random? in such a way as to new UUIDs be approximately inserted at the end of index.

**Comment by aztech-dev** [comment]
@Xerkus yes but in the test environment, the random part is left static (all 0's) to ensure that the timestamp is sequential. So the issue is purely related to the test environment, and should not happen in production (unless you override the default random generator with some funky implementation :) )

**Comment by Xerkus** [comment]
@aztech-dev I see. Then sleep() at the minimum precision used can solve it i suppose.

Also i see unrelated issue there. I need to check my facts, but isn't time dependent segment at the end of UUID will only have positive effect in mssql? If i understood rfc correctly, uuid is big endian, so that probably means that postgres uuid type will be as well.

**Comment by aztech-dev** [comment]
@Xerkus You're right. Current implementation is based off the "original" COMB implementation, which targets MSSQL. Improving it to support other databases shouldn't take too long...

**Comment by ramsey** [comment]
Lookin' good. :+1:

**Comment by ramsey** [comment]
@aztech-dev How's the improved COMB work coming along? :-)

**Comment by simensen** [comment]
@ramsey So is there actually a big here, then? I can't quite tell. :) I'm looking to either use this directly or find a way to borrow the implementation if I'm not able to use the newest version of ramsey/uuid.

Based on what @aztech-dev is saying, it sounds like this is only a problem in the test environment because the random part is static / all zeros in the test environment.

Mostly, I want to make sure this is actually a bug before I consider finding another solution. :) If this is only a bug in testing and safe in production, yay!

@aztech-dev also ping from me to find out how your patch is coming along for string vs MSSQL. :)

**Comment by ramsey** [comment]
Closing this issue.

@simensen, I've corrected the issue with the test, and have been unable to reproduce in a production environment. Indeed, this wouldn't happen in a production scenario, since the random bits wouldn't be static.

**Comment by ramsey** [comment]
@aztech-dev How's you're patch coming along? :-)

**Comment by aztech-dev** [comment]
Slowly, but surely :)
