### ISSUE TITLE
create DateTime with nanoseconds

### ISSUE THREAD

**Issue by thomasmuehlschlegel** [ramsey/uuid#90]
The uuid1 is using nanoseconds, but the UuidInterface returns a DateTime object which does not include the nanoseconds. 

DateTime can handle it if you adjust the initialization:

```
\DateTime::createFromFormat('U.u', sprintf('%.f', ($this->getTimestamp() - 0x01b21dd213814000) / 1e7))
```

**Comment by ramsey** [comment]
Unfortunately, this is failing our tests, since the `U` option does not support negative timestamps. I'm still looking into it, though.

**Comment by ramsey** [comment]
I spoke with Derick about it, and he has already fixed it in timelib. It will sync into PHP shortly: https://github.com/derickr/timelib/commit/483fbab1c83981a5573a1123f49ce5033da8775f

Derick supposes it will hit PHP versions 5.5.31 / 5.6.15 / 7.0.0RC6. Since we still support 5.4 (and versions earlier than 5.5.31 and 5.6.15) in this library, we may not be able to use this functionality for a while. I'm investigating other options.

**Comment by thomasmuehlschlegel** [comment]
Another try:

```
$unixTime = ($this->getTimestamp() - 0x01b21dd213814000) / 1e7;
$microTime = abs($unixTime * 1e6 - (int)$unixTime * 1e6);

return new \DateTime(date('Y-m-d H:i:s', (int)$unixTime) . '.' . (int)$microTime);
```

**Comment by ramsey** [comment]
I'm still working on this, but it's causing test failures, and I want to be careful, since changing the tests without considering the consequences in these cases could break software that depends on this library.

See #93 for the changes.

**Comment by ramsey** [comment]
Please see version 4.0.0-alpha1. The `getDateTime()` method now returns a `\DateTimeInterface` instance that includes the microseconds.

**Comment by azerpas** [comment]
> Please see version 4.0.0-alpha1. The `getDateTime()` method now returns a `\DateTimeInterface` instance that includes the microseconds.

How can we get 4.0.0 through composer? Waiting for that release for a project. 👍

**Comment by ramsey** [comment]
While the 4.0.0-alpha1 API is fairly stable, I don't recommend using it in production until the 4.0.0 release. That said, if you'd like to test it, I would recommend using this in your `composer.json`:

    "ramsey/uuid": "4.0.0-alpha1 as 4.0.0"
