### ISSUE TITLE
Add undashed parameter

### ISSUE THREAD

**Issue by Yamakasi** [ramsey/uuid#97]
Hi,

I created some simple function to create a undashed uuid when I need it and so something like undashedUuid("Vx");

Is it not an idea to implement this per default ?

**Comment by ramsey** [comment]
@Yamakasi, thanks for the recommendation. The `getHex()` method already supports this:

``` php
$uuid = \Ramsey\Uuid\Uuid::uuid4();
echo $uuid->getHex();
```

Alternately, if you already have a UUID, you may do this:

``` php
$uuid = \Ramsey\Uuid\Uuid::fromString('f6a1fd62-1445-42fc-9e7b-d8c6e9da33a1');
echo $uuid->getHex();
```

Let me know if this doesn't accomplish your goals.

**Comment by Yamakasi** [comment]
@ramsey Thanks! I wasn't aware of that, sorry! Would it be possible to that also like:

[code]
echo $uuid->uuid4()->getHex();

[/code]

^ Is a bad example, I know :)

**Comment by ramsey** [comment]
Sure thing:

    echo \Ramsey\Uuid\Uuid::uuid4()->getHex();

**Comment by Yamakasi** [comment]
Thanks! I removed the () from the v4 funtion because I wasn't sure!

Great added it to ZF2 using composer, all very good! thanks Gordon, oh no Ben :)

**Comment by ramsey** [comment]
Gordon spells Ramsay with an "a." ;-)

**Comment by Yamakasi** [comment]
I should read the PHP Cookbook better I guess ;)
Now testing it really makes HEX out of a UUID ? If so, the uuid itself undashed should be nice too, no ?

/me thinks you are really a friendly person, that's good in the PHP world :)

**Comment by ramsey** [comment]
A UUID is already in hexadecimal format (with or without the dashes), so the `getHex()` method simply returns the UUID without dashes. (A UUID is a 128-bit integer represented as a 32-character hexadecimal string, presented in a specific format using dashes to separate certain parts.)

Hope this helps. If not, please provide more information about what you're trying to accomplish, and I'll see if I can help.

**Comment by Yamakasi** [comment]
Kewl thanks for explaning!

**Comment by ramsey** [comment]
No problem. Glad to help!

**Comment by Yamakasi** [comment]
Ben, I would like to ask your opinion here, I know this bugtracker should not be used for this.

Is there really a need for the dashes or still that the sting is more readable ? I'm using these ID's for filenames and userID's and I think undashed is nicer in a DB than dashed. I can be wrong but I think you have a very plausible explanation about it.

Of course you can see, for a user, that dashed is a UUID and not some hash, but this should not matter or do you advise to use the dashes because of that ?

Sorry for asking :)

**Comment by ramsey** [comment]
No worries. I don't mind helping. :-)

The use of dashes is defined in [RFC 4122](http://tools.ietf.org/html/rfc4122) as the standard string representation of a UUID, but they're not required. It's up to you how you want to display or use them. It's just a 128-bit integer and can be represented in several different ways.

**Comment by Yamakasi** [comment]
Good to hear! Yes I just have to decide than, I already read the RFC about it.

Thanks!
