### ISSUE TITLE
Use with single file

### ISSUE THREAD

**Issue by Yamakasi** [ramsey/uuid#98]
Hi,

Is it possible to use your version using a single file without the composer part ?

file.php:

<?php

include(....);

// rest of script

Thanks!

**Comment by GrahamCampbell** [comment]
Just use composer's autoloader.

**Comment by Yamakasi** [comment]
As I said without composer at all.

**Comment by ramsey** [comment]
@Yamakasi You'll need some sort of autoloader, or you'll need to use `require_once` statements for every class in ramsey/uuid that needs to be loaded. My advice would be to have a script that includes all your `require_once` statements (i.e. `requires.php`) and at the top of each script in your application do `require 'requires.php';`.

The easiest route is to use Composer, but with some work, it is possible to do what you're asking.

**Comment by Yamakasi** [comment]
OK, clear enough. Composer is indeed nice when you can.

Thanks!
